export const words = {
  //-------------------- params -------------------//
  All: {
    en: "All",
    es: "Todos",
    fr: "Tous",
    de: "Alle",
    ru: "Все",
    da: "Alle",
    it: "Tutti",
    cs: "Všechny",
    nl: "Alle",
    no: "Alle",
    pl: "Wszystkie",
    sv: "Alla",
    tr: "Hepsi",
    uk: "Всі",
    ro: "Toate",
    bg: "Всички",
    be: "Tous",
    fi: "Kaikki",
    pt: "Todos",
    hr: "Svi",
    sl: "Vsi",
    el: "Όλα",
    hu: "Minden",
    sk: "Všetky",
    ga: "Gach",
    ja: "すべて",
    "zh-CN": "全部",
    "zh-TW": "全部",
    ko: "모두",
    ar: "الكل",
    ms: "Semua",
    th: "ทั้งหมด",
    vi: "Tất cả",
    tl: "Lahat",
    id: "Semua",
    ur: "سب",
    fa: "همه",
    my: "အားလုံး",
  },
  Coupon: {
    en: "Coupon",
    es: "Cupón",
    fr: "Coupon",
    de: "Gutschein",
    ru: "Купон",
    da: "Kupon", //  language - danish
    it: "Coupon",
    cs: "Kupón", //  language - czech
    nl: "Coupon",
    no: "Kupong",
    pl: "Kupon",
    sv: "Kupong", //   language - swedish
    tr: "Kupon",
    uk: "Купон", //  language - ukrainian
    ro: "Cupon",
    bg: "Купон",
    be: "Купон",
    fi: "Kuponki",
    pt: "Cupom",
    hr: "Kupon",
    sl: "Kupon", // slovekia
    el: "Κουπόνι", // language - greek
    hu: "Kupon",
    sk: "Kupón", //
    ga: "Cúipéan", //  language - irish
    ja: "クーポン", //
    "zh-CN": "优惠券", //
    "zh-TW": "優惠券", //
    ko: "쿠폰", //
    ar: "كوبون",
    ms: "Kupon", //malay
    th: "คูปอง", //thai
    vi: "Phiếu giảm giá", //vietnamese
    tl: "Kupon", //filipino
    id: "Kupon",
    ur: "کوپن",
    fa: "کوپن", //persian
    my: "ကုတ်", //burmese, myanmar
  },
  Coupons: {
    en: "Coupons",
    es: "Cupones",
    fr: "Coupons",
    de: "Gutscheine",
    ru: "Купоны",
    da: "Kuponer",
    it: "Coupon",
    cs: "Kupóny",
    nl: "Coupons",
    no: "Kuponger",
    pl: "Kupony",
    sv: "Kuponger",
    tr: "Kuponlar",
    uk: "Купони",
    ro: "Cupoane",
    bg: "Купони",
    be: "Купоны",
    fi: "Kupongit",
    pt: "Cupons",
    hr: "Kuponi",
    sl: "Kuponi",
    el: "Κουπόνια",
    hu: "Kuponok",
    sk: "Kupóny",
    ga: "Cúipéin",
    ja: "クーポン",
    "zh-CN": "优惠券",
    "zh-TW": "優惠券",
    ko: "쿠폰",
    ar: "كوبونات",
    ms: "Kupon",
    th: "คูปอง",
    vi: "Phiếu giảm giá", //vietnamese
    tl: "Kupon", //filipino
    id: "Kupon",
    ur: "کوپن",
    fa: "کوپن", //persian
    my: "ကုတ်",
  },
  CouponCode: {
    en: "Coupon Code",
    es: "Código de cupón",
    fr: "Code promo",
    de: "Gutscheincode",
    ru: "Промокод",
    da: "Kuponkode",
    it: "Codice coupon",
    cs: "Kód kupónu",
    nl: "Couponcode",
    no: "Kupongkode",
    pl: "Kod kuponu",
    sv: "Kupongkod",
    tr: "Kupon Kodu",
    uk: "Промокод",
    ro: "Cod de cupon",
    bg: "Код на купона",
    be: "Код купона",
    fi: "Kuponkoodi",
    pt: "Código do cupom",
    hr: "Kod kupona",
    sl: "Koda kupona",
    el: "Κωδικός κουπονιού",
    hu: "Kuponkód",
    sk: "Kód kupónu",
    ga: "Cód an chúipéin",
    ja: "クーポンコード",
    "zh-CN": "优惠券代码", //
    "zh-TW": "優惠券代碼", //
    ko: "쿠폰 코드",
    ar: "رمز الكوبون",
    ms: "Kod kupon",
    th: "รหัสคูปอง",
    vi: "Mã giảm giá",
    tl: "Coupon Code",
    id: "Kode Kupon",
    ur: "کوپن کوڈ",
    fa: "کد کوپن",
    my: "ကုတ်ကုဒ်",
  },
  Deal: {
    en: "Deal",
    es: "Trato",
    fr: "Affaire",
    de: "Deal",
    ru: "Сделка",
    da: "Aftale",
    it: "Affare",
    cs: "Obchod",
    nl: "Deal",
    no: "Avtale",
    pl: "Umowa",
    sv: "Affär",
    tr: "Anlaşma",
    uk: "Угода",
    ro: "Tranzacție",
    bg: "Сделка",
    be: "Угода",
    fi: "Sopimus",
    pt: "Negócio",
    hr: "Posao",
    sl: "Posel",
    el: "Συμφωνία",
    hu: "Üzlet",
    sk: "Obchod",
    ga: "Deil",
    ja: "ディール",
    "zh-CN": "交易",
    "zh-TW": "交易",
    ko: "딜",
    ar: "صفقة",
    ms: "Pakatan",
    th: "ดีล",
    vi: "Giao dịch",
    tl: "Deal",
    id: "Perjanjian",
    ur: "ڈیل",
    fa: "معامله",
    my: "ငွေစျေး",
  },
  Deals: {
    //give me all languages word that are given above
    en: "Deals",
    es: "Ofertas",
    fr: "Offres",
    de: "Angebote",
    ru: "Сделки",
    da: "Aftaler",
    it: "Affari",
    cs: "Deály",
    nl: "Deals",
    no: "Tilbud",
    pl: "Oferty",
    sv: "Affärer",
    tr: "Fırsatlar",
    uk: "Угоди",
    ro: "Oferte",
    bg: "Сделки",
    be: "Угоды",
    fi: "Sopimukset",
    pt: "Ofertas",
    hr: "Poslovi",
    sl: "Posli",
    el: "Συμφωνίες",
    hu: "Üzletek",
    sk: "Obchody",
    ga: "Deals",
    ja: "ディール",
    "zh-CN": "交易",
    "zh-TW": "交易",
    ko: "딜",
    ar: "صفقات",
    ms: "Pakatan",
    th: "ดีล",
    vi: "Giao dịch",
    tl: "Deal",
    id: "Perjanjian",
    ur: "ڈیل",
    fa: "معاملات",
    my: "ငွေစျေး",
  },

  //-------------------- navbar -------------------//

  Home: {
    en: "Home",
    es: "Casa",
    fr: "Accueil",
    de: "Zuhause",
    ru: "Главная",
    da: "Hjem",
    it: "Casa",
    cs: "Domov",
    nl: "Huis",
    no: "Hjem",
    pl: "Dom",
    sv: "Hem",
    tr: "Ev",
    uk: "Дім",
    ro: "Acasă",
    bg: "У дома",
    be: "Дома",
    fi: "Koti",
    pt: "Casa",
    hr: "Kuća",
    sl: "Doma",
    el: "Σπίτι",
    hu: "Otthon",
    sk: "Domov",
    ga: "Baile",
    ja: "家",
    "zh-CN": "家",
    "zh-TW": "家",
    ko: "집",
    ar: "الصفحة الرئيسية",
    ms: "Rumah",
    th: "บ้าน",
    vi: "Nhà",
    tl: "Bahay",
    id: "Rumah",
    ur: "گھر",
    fa: "خانه",
    my: "အိမ်",
  },
  Stores: {
    en: "Stores",
    es: "Tiendas",
    fr: "Magasins",
    de: "Geschäfte",
    ru: "Магазины",
    da: "Butikker",
    it: "Negozi",
    cs: "Obchody",
    nl: "Winkels",
    no: "Butikker",
    pl: "Sklepy",
    sv: "Butiker",
    tr: "Mağazalar",
    uk: "Магазини",
    ro: "Magazine",
    bg: "Магазини",
    be: "Магазіны",
    fi: "Kaupat",
    pt: "Lojas",
    hr: "Trgovine",
    sl: "Trgovine",
    el: "Καταστήματα",
    hu: "Üzletek",
    sk: "Obchody",
    ga: "Siopaí",
    ja: "店舗",
    "zh-CN": "商店",
    "zh-TW": "商店",
    ko: "상점",
    ar: "متاجر",
    ms: "Kedai",
    th: "ร้านค้า",
    vi: "Cửa hàng",
    tl: "Mga tindahan",
    id: "Toko",
    ur: "اسٹورز",
    fa: "فروشگاه ها",
    my: "ဆိုင်များ",
  },
  TopBrands: {
    en: "Top Brands",
    es: "Mejores marcas",
    fr: "Meilleures marques",
    de: "Top-Marken",
    ru: "Лучшие бренды",
    da: "Topmærker",
    it: "Top Brands",
    cs: "Top Brands",
    nl: "Topmerken",
    no: "Toppmerker",
    pl: "Najlepsze marki",
    sv: "Top Märken",
    tr: "En İyi Markalar",
    uk: "Топ-бренди",
    ro: "Mărci de top",
    bg: "Топ марки",
    be: "Лепшыя брэнды",
    fi: "Parhaat merkit",
    pt: "Melhores marcas",
    hr: "Najbolje marke",
    sl: "Najboljše znamke",
    el: "Κορυφαία Brands",
    hu: "Legjobb márkák",
    sk: "Top Brands",
    ga: "Top Brands",
    ja: "トップブランド",
    "zh-CN": "热门品牌",
    "zh-TW": "熱門品牌",
    ko: "인기 브랜드",
    ar: "أفضل العلامات التجارية",
    ms: "Jenama Teratas",
    th: "ยอดนิยมแบรนด์",
    vi: "Thương hiệu hàng đầu",
    tl: "Mga Top na Brand",
    id: "Merek Teratas",
    ur: "بہترین برانڈز",
    fa: "برندهای برتر",
    my: "အဆိုပါအမျိုးအစား",
  },
  TopOffers: {
    en: "Top Offers",
    es: "Mejores ofertas",
    fr: "Meilleures offres",
    de: "Top-Angebote",
    ru: "Лучшие предложения",
    da: "Top tilbud",
    it: "Top Offers",
    cs: "Top Offers",
    nl: "Topaanbiedingen",
    no: "Tilbud",
    pl: "Najlepsze oferty",
    sv: "Top Offers",
    tr: "En İyi Teklifler",
    uk: "Топ пропозиції",
    ro: "Cele mai bune oferte",
    bg: "Топ оферти",
    be: "Лепшыя прапановы",
    fi: "Parhaat tarjoukset",
    pt: "Melhores ofertas",
    hr: "Najbolje ponude",
    sl: "Najboljše ponudbe",
    el: "Κορυφαίες προσφορές",
    hu: "Legjobb ajánlatok",
    sk: "Top Offers",
    ga: "Top Offers",
    ja: "トップオファー",
    "zh-CN": "热门优惠",
    "zh-TW": "熱門優惠",
    ko: "인기 상품",
    ar: "أفضل العروض",
    ms: "Tawaran Teratas",
    th: "ดีลยอดนิยม",
    vi: "Ưu đãi hàng đầu",
    tl: "Mga Top na Alok",
    id: "Penawaran Teratas",
    ur: "بہترین پیشکشیں",
    fa: "بهترین پیشنهادات",
    my: "အဆိုပါအမျိုးအစား",
  },

  Categories: {
    en: "Categories",
    es: "Categorías",
    fr: "Catégories",
    de: "Kategorien",
    ru: "Категории",
    da: "Kategorier",
    it: "Categorie",
    cs: "Kategorie",
    nl: "Categorieën",
    no: "Kategorier",
    pl: "Kategorie",
    sv: "Kategorier",
    tr: "Kategoriler",
    uk: "Категорії",
    ro: "Categorii",
    bg: "Категории",
    be: "Катэгорыі",
    fi: "Kategoriat",
    pt: "Categorias",
    hr: "Kategorije",
    sl: "Kategorije",
    el: "Κατηγορίες",
    hu: "Kategóriák",
    sk: "Kategórie",
    ga: "Catagóirí",
    ja: "カテゴリー",
    "zh-CN": "分类",
    "zh-TW": "分類",
    ko: "카테고리",
    ar: "التصنيفات",
    ms: "Kategori",
    th: "หมวดหมู่",
    vi: "Danh mục",
    tl: "Mga Kategorya",
    id: "Kategori",
    ur: "زمرے",
    fa: "دسته بندی ها",
    my: "အမျိုးအစား",
  },
  Search: {
    en: "Search",
    es: "Buscar",
    fr: "Chercher",
    de: "Suche",
    ru: "Поиск",
    da: "Søg",
    it: "Ricerca",
    cs: "Vyhledávání",
    nl: "Zoeken",
    no: "Søk",
    pl: "Szukaj",
    sv: "Sök",
    tr: "Arama",
    uk: "Пошук",
    ro: "Căutare",
    bg: "Търсене",
    be: "Пошук",
    fi: "Haku",
    pt: "Procurar",
    hr: "Pretraživanje",
    sl: "Iskanje",
    el: "Αναζ",
    hu: "Keresés",
    sk: "Vyhľadávanie",
    ga: "Cuardaigh",
    ja: "サーチ",
    "zh-CN": "搜索",
    "zh-TW": "搜索",
    ko: "검색",
    ar: "بحث",
    ms: "Cari",
    th: "ค้นหา",
    vi: "Tìm kiếm",
    tl: "Maghanap",
    id: "Cari",
    ur: "تلاش کریں",
    fa: "جستجو",
    my: "ရှာဖွေပါ",
  },
  AddDeal: {
    en: "Add Deal",
    es: "Agregar oferta",
    fr: "Ajouter une affaire",
    de: "Deal hinzufügen",
    ru: "Добавить сделку",
    da: "Tilføj aftale",
    it: "Aggiungi affare",
    cs: "Přidat obchod",
    nl: "Deal toevoegen",
    no: "Legg til avtale",
    pl: "Dodaj ofertę",
    sv: "Lägg till affär",
    tr: "Anlaşma Ekle",
    uk: "Додати угоду",
    ro: "Adăugați afacere",
    bg: "Добавете сделка",
    be: "Дадаць справу",
    fi: "Lisää diili",
    pt: "Adicionar negócio",
    hr: "Dodaj posao",
    sl: "Dodaj posel",
    el: "Προσθήκη συμφωνίας",
    hu: "Üzlet hozzáadása",
    sk: "Pridať obchod",
    ga: "Cuir Deal leis",
    ja: "ディールを追加",
    "zh-CN": "添加交易",
    "zh-TW": "添加交易",
    ko: "딜 추가",
    ar: "إضافة صفقة",
    ms: "Tambah Pakej",
    th: "เพิ่มดีล",
    vi: "Thêm Giao dịch",
    tl: "Magdagdag ng Deal",
    id: "Tambahkan Deal",
    ur: "ڈیل شامل کریں",
    fa: "افزودن معامله",
    my: "ငွေစျေးထည့်ပါ",
  },

  //-------------------- footer -------------------//

  HaveANiceDay: {
    en: "Have a Nice Day",
    es: "Que tengas un buen día",
    fr: "Passe une bonne journée",
    de: "Haben Sie einen schönen Tag",
    ru: "Хорошего дня",
    da: "Hav en god dag",
    it: "Buona giornata",
    cs: "Hezký den",
    nl: "Fijne dag",
    no: "Ha en fin dag",
    pl: "Miłego dnia",
    sv: "Ha en trevlig dag",
    tr: "İyi günler",
    uk: "Гарного дня",
    ro: "O zi frumoasă",
    bg: "Хубав ден",
    be: "Добры дзень",
    fi: "Hyvää päivää",
    pt: "Tenha um bom dia",
    hr: "Imaj lijep dan",
    sl: "Imej lep dan",
    el: "Να έχετε μια ωραία μέρα",
    hu: "Legyen szép napod",
    sk: "Majte pekný deň",
    ga: "Bíodh lá maith agat",
    ja: "良い一日を",
    "zh-CN": "祝你有个美好的一天",
    "zh-TW": "祝你有個美好的一天",
    ko: "좋은 하루 되세요",
    ar: "أتمنى لك يومًا جميلًا",
    ms: "Semoga Harimu Menyenangkan",
    th: "ขอให้คุณมีวันที่ดี",
    vi: "Chúc bạn một ngày tốt lành",
    tl: "Magandang Araw",
    id: "Selamat Hari",
    ur: "ایک خوبصورت دن ہو",
    fa: "یک روز خوبی داشته باشید",
    my: "မင်္ဂလာနေ့ရဲ့အတွက်ဖြစ်ပါတယ်",
  },
  GlobalNetwork: {
    en: "Global Network",
    es: "Red global",
    fr: "Réseau mondial",
    de: "Globales Netzwerk",
    ru: "Глобальная сеть",
    da: "Globalt netværk",
    it: "Rete globale",
    cs: "Globální síť",
    nl: "Wereldwijd netwerk",
    no: "Globalt nettverk",
    pl: "Globalna sieć",
    sv: "Globalt nätverk",
    tr: "Global Ağ",
    uk: "Глобальна мережа",
    ro: "Rețea globală",
    bg: "Глобална мрежа",
    be: "Глабальная сетка",
    fi: "Maailmanlaajuinen verkosto",
    pt: "Rede global",
    hr: "Globalna mreža",
    sl: "Globalno omrežje",
    el: "Παγκόσμιο δίκτυο",
    hu: "Globális hálózat",
    sk: "Celosvetová sieť",
    ga: "Líonra Domhanda",
    ja: "グローバルネットワーク",
    "zh-CN": "全球网络",
    "zh-TW": "全球網絡",
    ko: "글로벌 네트워크",
    ar: "شبكة عالمية",
    ms: "Rangkaian Global",
    th: "เครือข่ายโลก",
    vi: "Mạng lưới toàn cầu",
    tl: "Global Network",
    id: "Jaringan Global",
    ur: "عالمی نیٹ ورک",
    fa: "شبکه جهانی",
    my: "ကမ္ဘာ့ကွန်ယက်",
  },
  ImportantLinks: {
    en: "Important Links",
    es: "Enlaces importantes",
    fr: "Liens importants",
    de: "Wichtige Links",
    ru: "Важные ссылки",
    da: "Vigtige links",
    it: "Link importanti",
    cs: "Důležité odkazy",
    nl: "Belangrijke links",
    no: "Viktige linker",
    pl: "Ważne linki",
    sv: "Viktiga länkar",
    tr: "Önemli Bağlantılar",
    uk: "Важливі посилання",
    ro: "Linkuri importante",
    bg: "Важни връзки",
    be: "Важныя спасылкі",
    fi: "Tärkeät linkit",
    pt: "Links importantes",
    hr: "Važne poveznice",
    sl: "Pomembne povezave",
    el: "Σημαντικοί σύνδεσμοι",
    hu: "Fontos linkek",
    sk: "Dôležité odkazy",
    ga: "Naisc Tábhachtach",
    ja: "重要なリンク",
    "zh-CN": "重要链接",
    "zh-TW": "重要鏈接",
    ko: "중요한 링크",
    ar: "روابط مهمة",
    ms: "Pautan Penting",
    th: "ลิงก์ที่สำคัญ",
    vi: "Liên kết quan trọng",
    tl: "Mahalagang Mga Link",
    id: "Tautan Penting",
    ur: "اہم لنکس",
    fa: "پیوندهای مهم",
    my: "အရင်းအမြစ်များ",
  },
  AboutUs: {
    en: "About Us",
    es: "Sobre nosotros",
    fr: "À propos de nous",
    de: "Über uns",
    ru: "О нас",
    da: "Om os",
    it: "Riguardo a noi",
    cs: "O nás",
    nl: "Over ons",
    no: "Om oss",
    pl: "O nas",
    sv: "Om oss",
    tr: "Hakkımızda",
    uk: "Про нас",
    ro: "Despre noi",
    bg: "За нас",
    be: "Пра нас",
    fi: "Meistä",
    pt: "Sobre nós",
    hr: "O nama",
    sl: "O nas",
    el: "Σχετικά μαζί μας",
    hu: "Rólunk",
    sk: "O nás",
    ga: "Maidir linn",
    ja: "私たちについて",
    "zh-CN": "关于我们",
    "zh-TW": "關於我們",
    ko: "우리에 관하여",
    ar: "عنا",
    ms: "Tentang Kami",
    th: "เกี่ยวกับเรา",
    vi: "Về chúng tôi",
    tl: "Tungkol sa amin",
    id: "Tentang Kami",
    ur: "ہمارے بارے میں",
    fa: "درباره ما",
    my: "ကျွန်ုပ်တို့အေၾကာင္း",
  },
  ContactUs: {
    en: "Contact Us",
    es: "Contáctenos",
    fr: "Contactez nous",
    de: "Kontaktiere uns",
    ru: "Свяжитесь с нами",
    da: "Kontakt os",
    it: "Contattaci",
    cs: "Kontaktujte nás",
    nl: "Contact met ons opnemen",
    no: "Kontakt oss",
    pl: "Skontaktuj się z nami",
    sv: "Kontakta oss",
    tr: "Bizimle iletişime geçin",
    uk: "Зв'яжіться з нами",
    ro: "Contactează-ne",
    bg: "Свържете се с нас",
    be: "Звяжыцеся з намі",
    fi: "Ota meihin yhteyttä",
    pt: "Entre em contato conosco",
    hr: "Kontaktirajte nas",
    sl: "Kontaktirajte nas",
    el: "Επικοινωνήστε μαζί μας",
    hu: "Lépjen kapcsolatba velünk",
    sk: "Kontaktujte nás",
    ga: "Déan teagmháil linn",
    ja: "お問い合わせ",
    "zh-CN": "联系我们",
    "zh-TW": "聯繫我們",
    ko: "문의하기",
    ar: "اتصل بنا",
    ms: "Hubungi Kami",
    th: "ติดต่อเรา",
    vi: "Liên hệ với chúng tôi",
    tl: "Makipag-ugnayan sa amin",
    id: "Hubungi Kami",
    ur: "ہم سے رابطہ کریں",
    fa: "با ما تماس بگیرید",
    my: "ဆက်သွယ်ပါ",
  },
  PrivacyPolicy: {
    en: "Privacy Policy",
    es: "Política de privacidad",
    fr: "Politique de confidentialité",
    de: "Datenschutz-Bestimmungen",
    ru: "Политика конфиденциальности",
    da: "Fortrolighedspolitik",
    it: "Informativa sulla privacy",
    cs: "Zásady ochrany osobních údajů",
    nl: "Privacybeleid",
    no: "Personvernregler",
    pl: "Polityka prywatności",
    sv: "Integritetspolicy",
    tr: "Gizlilik Politikası",
    uk: "Політика конфіденційності",
    ro: "Politica de confidențialitate",
    bg: "Политика за поверителност",
    be: "Палітыка прыватнасці",
    fi: "Tietosuojakäytännöt",
    pt: "Política de Privacidade",
    hr: "Pravila o privatnosti",
    sl: "Pravilnik o zasebnosti",
    el: "Πολιτική απορρήτου",
    hu: "Adatvédelmi irányelvek",
    sk: "Zásady ochrany osobných údajov",
    ga: "Polasaí Príobháideachta",
    ja: "プライバシーポリシー",
    "zh-CN": "隐私政策",
    "zh-TW": "隱私政策",
    ko: "개인정보 보호 정책",
    ar: "سياسة الخصوصية",
    ms: "Dasar Privasi",
    th: "นโยบายความเป็นส่วนตัว",
    vi: "Chính sách bảo mật",
    tl: "Patakaran sa Privacy",
    id: "Kebijakan Privasi",
    ur: "پرائیویسی پالیسی",
    fa: "سیاست حفظ حریم خصوصی",
    my: "လုံခြုံရေးပါတီ",
  },
  TermsAndConditions: {
    en: "Terms and Conditions",
    es: "Términos y condiciones",
    fr: "Termes et conditions",
    de: "Allgemeine Geschäftsbedingungen",
    ru: "Условия и положения",
    da: "Vilkår og betingelser",
    it: "Termini e condizioni",
    cs: "Obchodní podmínky",
    nl: "Algemene voorwaarden",
    no: "Vilkår og betingelser",
    pl: "Regulamin",
    sv: "Villkor och bestämmelser",
    tr: "Şartlar ve koşullar",
    uk: "Умови та положення",
    ro: "Termeni și condiții",
    bg: "Общи условия",
    be: "Умовы і палажэнні",
    fi: "Käyttöehdot",
    pt: "Termos e Condições",
    hr: "Uvjeti i odredbe",
    sl: "Pogoji in določila",
    el: "Όροι και Προϋποθέσεις",
    hu: "Felhasználási feltételek",
    sk: "Obchodné podmienky",
    ga: "Teorainneacha agus Coinníollacha",
    ja: "利用規約",
    "zh-CN": "条款和条件",
    "zh-TW": "條款和條件",
    ko: "이용 약관",
    ar: "البنود و الشروط",
    ms: "Terma dan Syarat",
    th: "ข้อกำหนดและเงื่อนไข",
    vi: "Điều khoản và Điều kiện",
    tl: "Mga Tuntunin at Kondisyon",
    id: "Syarat dan Ketentuan",
    ur: "شرائط و ضوابط",
    fa: "شرایط و ضوابط",
    my: "စည်းမျဉ်းနှင့်စည်းမျဉ်းများ",
  },
  Disclaimer: {
    en: "Disclaimer",
    es: "Descargo de responsabilidad",
    fr: "Avertissement",
    de: "Haftungsausschluss",
    ru: "Отказ от ответственности",
    da: "Ansvarsfraskrivelse",
    it: "Disclaimer",
    cs: "Odmítnutí odpovědnosti",
    nl: "Disclaimer",
    no: "Ansvarsfraskrivelse",
    pl: "Oświadczenie",
    sv: "Ansvarsfriskrivning",
    tr: "Reddi",
    uk: "Відмова від відповідальності",
    ro: "Renunțare",
    bg: "Отказ от отговорност",
    be: "Адмова ад адказнасці",
    fi: "Vastuuvapauslauseke",
    pt: "Isenção de responsabilidade",
    hr: "Ograničenje odgovornosti",
    sl: "Oprostitev odgovornosti",
    el: "Αποποίηση ευθύνης",
    hu: "Felelősségmentesítés",
    sk: "Zrieknutie sa zodpovednosti",
    ga: "Diúltú",
    ja: "免責事項",
    "zh-CN": "免责声明",
    "zh-TW": "免責聲明",
    ko: "면책 성명",
    ar: "إخلاء المسؤولية",
    ms: "Penafian",
    th: "คำปฏิเสธความรับผิด",
    vi: "Miễn trừ trách nhiệm",
    tl: "Disclaimer",
    id: "Penafian",
    ur: "تنبیہ",
    fa: "سلب مسئولیت",
    my: "သော့ချက်",
  },
  AllStores: {
    en: "All Stores",
    es: "Todas las tiendas",
    fr: "Tous les magasins",
    de: "Alle Geschäfte",
    ru: "Все магазины",
    da: "Alle butikker",
    it: "Tutti i negozi",
    cs: "Všechny obchody",
    nl: "Alle winkels",
    no: "Alle butikker",
    pl: "Wszystkie sklepy",
    sv: "Alla butiker",
    tr: "Tüm mağazalar",
    uk: "Всі магазини",
    ro: "Toate magazinele",
    bg: "Всички магазини",
    be: "Усе магазіны",
    fi: "Kaikki kaupat",
    pt: "Todas as lojas",
    hr: "Sve trgovine",
    sl: "Vse trgovine",
    el: "Όλα τα καταστήματα",
    hu: "Minden üzlet",
    sk: "Všetky obchody",
    ga: "Gach Siopa",
    ja: "すべての店舗",
    "zh-CN": "所有商店",
    "zh-TW": "所有商店",
    ko: "모든 상점",
    ar: "جميع المتاجر",
    ms: "Semua Kedai",
    th: "ร้านค้าทั้งหมด",
    vi: "Tất cả cửa hàng",
    tl: "Lahat ng Tindahan",
    id: "Semua Toko",
    ur: "تمام اسٹورز",
    fa: "تمام فروشگاه ها",
    my: "ဆိုင်များအားလုံး",
  },
  TopStores: {
    en: "Top Stores",
    es: "Tiendas principales",
    fr: "Meilleurs magasins",
    de: "Top-Geschäfte",
    ru: "Лучшие магазины",
    da: "Topbutikker",
    it: "Negozi migliori",
    cs: "Top obchody",
    nl: "Topwinkels",
    no: "Toppbutikker",
    pl: "Najlepsze sklepy",
    sv: "Topbutiker",
    tr: "En İyi Mağazalar",
    uk: "Топ магазини",
    ro: "Cele mai bune magazine",
    bg: "Топ магазини",
    be: "Лепшыя магазіны",
    fi: "Parhaat kaupat",
    pt: "Melhores lojas",
    hr: "Najbolje trgovine",
    sl: "Najboljše trgovine",
    el: "Κορυφαία καταστήματα",
    hu: "Legjobb üzletek",
    sk: "Top obchody",
    ga: "Top Stores",
    ja: "トップストア",
    "zh-CN": "热门商店",
    "zh-TW": "熱門商店",
    ko: "인기 상점",
    ar: "أفضل المتاجر",
    ms: "Kedai Teratas",
    th: "ร้านค้ายอดนิยม",
    vi: "Cửa hàng hàng đầu",
    tl: "Mga Top na Tindahan",
    id: "Toko Teratas",
    ur: "بہترین اسٹورز",
    fa: "برترین فروشگاه ها",
    my: "အဆိုပါဆိုင်များ",
  },
  BestOffers: {
    en: "Best Offers",
    es: "Mejores ofertas",
    fr: "Meilleures offres",
    de: "Beste Angebote",
    ru: "Лучшие предложения",
    da: "Bedste tilbud",
    it: "Migliori offerte",
    cs: "Nejlepší nabídky",
    nl: "Beste aanbiedingen",
    no: "Beste tilbud",
    pl: "Najlepsze oferty",
    sv: "Bästa erbjudanden",
    tr: "En İyi Teklifler",
    uk: "Кращі пропозиції",
    ro: "Cele mai bune oferte",
    bg: "Най-добрите оферти",
    be: "Лепшыя прапановы",
    fi: "Parhaat tarjoukset",
    pt: "Melhores ofertas",
    hr: "Najbolje ponude",
    sl: "Najboljše ponudbe",
    el: "Καλύτερες προσφορές",
    hu: "Legjobb ajánlatok",
    sk: "Najlepšie ponuky",
    ga: "Cuir Deal leis",
    ja: "ベストオファー",
    "zh-CN": "最佳优惠",
    "zh-TW": "最佳優惠",
    ko: "최고의 제안",
    ar: "أفضل العروض",
    ms: "Tawaran Terbaik",
    th: "ดีลที่ดีที่สุด",
    vi: "Ưu đãi tốt nhất",
    tl: "Mga Pinakamahusay na Alo",
    id: "Penawaran Terbaik",
    ur: "بہترین پیشکشیں",
    fa: "بهترین پیشنهادات",
    my: "အဆိုပါအမျိုးအစား",
  },
  SubmitACoupon: {
    en: "Submit a Coupon",
    es: "Enviar un cupón",
    fr: "Soumettre un coupon",
    de: "Gutschein einreichen",
    ru: "Отправить купон",
    da: "Indsend en kupon",
    it: "Invia un coupon",
    cs: "Odeslat kupón",
    nl: "Een coupon indienen",
    no: "Send inn en kupong",
    pl: "Prześlij kupon",
    sv: "Skicka in en kupong",
    tr: "Kupon Gönder",
    uk: "Надіслати купон",
    ro: "Trimiteți un cupon",
    bg: "Изпратете купон",
    be: "Адправіць купон",
    fi: "Lähetä kuponki",
    pt: "Enviar um cupom",
    hr: "Pošaljite kupon",
    sl: "Pošlji kupon",
    el: "Υποβολή κουπονιού",
    hu: "Küldjön be egy kupont",
    sk: "Odoslať kupón",
    ga: "Cuir Cupán isteach",
    ja: "クーポンを提出する",
    "zh-CN": "提交优惠券",
    "zh-TW": "提交優惠券",
    ko: "쿠폰 제출",
    ar: "إرسال قسيمة",
    ms: "Hantar Kupon",
    th: "ส่งคูปอง",
    vi: "Gửi phiếu giảm giá",
    tl: "Magsumite ng Kupon",
    id: "Kirim Kupon",
    ur: "ایک کوپن جمع کروائیں",
    fa: "ثبت کوپن",
    my: "ကူပွန်တင်ပါ",
  },

  //-------------------- auth -------------------//

  Login: {
    en: "Login",
    es: "Iniciar sesión",
    fr: "S'identifier",
    de: "Anmeldung",
    ru: "Авторизоваться",
    da: "Log på",
    it: "Accesso",
    cs: "Přihlášení",
    nl: "Log in",
    no: "Logg inn",
    pl: "Zaloguj się",
    sv: "Logga in",
    tr: "Oturum aç",
    uk: "Увійти",
    ro: "Autentificare",
    bg: "Вход",
    be: "Увайсці",
    fi: "Kirjaudu sisään",
    pt: "Entrar",
    hr: "Prijava",
    sl: "Prijava",
    el: "Σύνδεση",
    hu: "Bejelentkezés",
    sk: "Prihlásenie",
    ga: "Logáil isteach",
    ja: "ログイン",
    "zh-CN": "登录",
    "zh-TW": "登錄",
    ko: "로그인",
    ar: "تسجيل الدخول",
    ms: "Log Masuk",
    th: "เข้าสู่ระบบ",
    vi: "Đăng nhập",
    tl: "Mag-login",
    id: "Masuk",
    ur: "لاگ ان",
    fa: "ورود",
    my: "ဝင်ရောက်ရန်",
  },
  or: {
    en: "or",
    es: "o",
    fr: "ou",
    de: "oder",
    ru: "или",
    da: "eller",
    it: "o",
    cs: "nebo",
    nl: "of",
    no: "eller",
    pl: "lub",
    sv: "eller",
    tr: "veya",
    uk: "або",
    ro: "sau",
    bg: "или",
    be: "ці",
    fi: "tai",
    pt: "ou",
    hr: "ili",
    sl: "ali",
    el: "ή",
    hu: "vagy",
    sk: "alebo",
    ga: "nó",
    ja: "または",
    "zh-CN": "要么",
    "zh-TW": "要么",
    ko: "또는",
    ar: "أو",
    ms: "atau",
    th: "หรือ",
    vi: "hoặc",
    tl: "o",
    id: "atau",
    ur: "یا",
    fa: "یا",
    my: "သို့သော်",
  },
  Signup: {
    en: "Signup",
    es: "Regístrate",
    fr: "S'inscrire",
    de: "Anmelden",
    ru: "Зарегистрироваться",
    da: "Tilmeld dig",
    it: "Iscriviti",
    cs: "Přihlásit se",
    nl: "Aanmelden",
    no: "Registrer deg",
    pl: "Zarejestruj się",
    sv: "Registrera dig",
    tr: "Kaydol",
    uk: "Зареєструватися",
    ro: "Înscrie-te",
    bg: "Регистрирай се",
    be: "Зарэгістравацца",
    fi: "Rekisteröidy",
    pt: "Inscrever-se",
    hr: "Prijavite se",
    sl: "Prijavite se",
    el: "Εγγραφείτε",
    hu: "Regisztrálj",
    sk: "Registrovať sa",
    ga: "Cláraigh",
    ja: "サインアップ",
    "zh-CN": "注册",
    "zh-TW": "註冊",
    ko: "가입",
    ar: "سجل",
    ms: "Daftar",
    th: "ลงทะเบียน",
    vi: "Đăng ký",
    tl: "Mag-sign Up",
    id: "Daftar",
    ur: "سائن اپ",
    fa: "ثبت نام",
    my: "အကောင့်များ",
  },
  Logout: {
    en: "Logout",
    es: "Cerrar sesión",
    fr: "Se déconnecter",
    de: "Ausloggen",
    ru: "Выйти",
    da: "Log ud",
    it: "Disconnettersi",
    cs: "Odhlásit se",
    nl: "Uitloggen",
    no: "Logg ut",
    pl: "Wyloguj się",
    sv: "Logga ut",
    tr: "Çıkış yap",
    uk: "Вийти",
    ro: "Deconectare",
    bg: "Излез",
    be: "Выйсці",
    fi: "Kirjaudu ulos",
    pt: "Sair",
    hr: "Odjava",
    sl: "Odjava",
    el: "Αποσύνδεση",
    hu: "Kijelentkezés",
    sk: "Odhlásiť sa",
    ga: "Logáil Amach",
    ja: "ログアウト",
    "zh-CN": "登出",
    "zh-TW": "登出",
    ko: "로그 아웃",
    ar: "تسجيل الخروج",
    ms: "Log Keluar",
    th: "ออกจากระบบ",
    vi: "Đăng xuất",
    tl: "Mag-logout",
    id: "Keluar",
    ur: "لاگ آوٹ",
    fa: "خروج",
    my: "ထွက်ရန်",
  },
  //-------------------- storepage -------------------//
  Ratings: {
    en: "Ratings",
    es: "Calificaciones",
    fr: "Évaluations",
    de: "Bewertungen",
    ru: "Рейтинги",
    da: "Bedømmelser",
    it: "Valutazioni",
    cs: "Hodnocení",
    nl: "Beoordelingen",
    no: "Vurderinger",
    pl: "Oceny",
    sv: "Betyg",
    tr: "Derecelendirmeler",
    uk: "Рейтинги",
    ro: "Evaluări",
    bg: "Рейтинги",
    be: "Рэйтынгі",
    fi: "Arviot",
    pt: "Avaliações",
    hr: "Ocjene",
    sl: "Ocene",
    el: "Αξιολογήσεις",
    hu: "Értékelések",
    sk: "Hodnotenia",
    ga: "Rátálacha",
    ja: "評価",
    "zh-CN": "评级",
    "zh-TW": "評級",
    ko: "평가",
    ar: "تصنيفات",
    ms: "Penilaian",
    th: "การจัดอันดับ",
    vi: "Đánh giá",
    tl: "Mga Rating",
    id: "Peringkat",
    ur: "درجے",
    fa: "رتبه بندی",
    my: "အဆင့်များ",
  },
  Content: {
    en: "Content",
    es: "Contenido",
    fr: "Contenu",
    de: "Inhalt",
    ru: "Содержание",
    da: "Indhold",
    it: "Contenuto",
    cs: "Obsah",
    nl: "Inhoud",
    no: "Innhold",
    pl: "Zawartość",
    sv: "Innehåll",
    tr: "İçerik",
    uk: "Зміст",
    ro: "Conținut",
    bg: "Съдържание",
    be: "Змест",
    fi: "Sisältö",
    pt: "Conteúdo",
    hr: "Sadržaj",
    sl: "Vsebina",
    el: "Περιεχόμενο",
    hu: "Tartalom",
    sk: "Obsah",
    ga: "Ábhar",
    ja: "コンテンツ",
    "zh-CN": "内容",
    "zh-TW": "內容",
    ko: "콘텐츠",
    ar: "محتوى",
    ms: "Kandungan",
    th: "เนื้อหา",
    vi: "Nội dung",
    tl: "Nilalaman",
    id: "Konten",
    ur: "مواد",
    fa: "محتوا",
    my: "ပါတီ",
  },

  Visit: {
    en: "Visit",
    es: "Visita",
    fr: "Visite",
    de: "Besuch",
    ru: "Посещение",
    da: "Besøg",
    it: "Visita",
    cs: "Návštěva",
    nl: "Bezoek",
    no: "Besøk",
    pl: "Wizyta",
    sv: "Besök",
    tr: "Ziyaret",
    uk: "Візит",
    ro: "Vizită",
    bg: "Посещение",
    be: "Візіт",
    fi: "Vierailu",
    pt: "Visita",
    hr: "Posjeta",
    sl: "Obisk",
    el: "Επίσκεψη",
    hu: "Látogatás",
    sk: "Návšteva",
    ga: "Cuairt",
    ja: "訪問",
    "zh-CN": "访问",
    "zh-TW": "訪問",
    ko: "방문",
    ar: "زيارة",
    ms: "Melawat",
    th: "เยี่ยม",
    vi: "Thăm",
    tl: "Pumunta",
    id: "Kunjungi",
    ur: "دورہ",
    fa: "بازدید",
    my: "ကြိုက်ရှာပါ",
  },
  IsItWorking: {
    en: "Is It Working?",
    es: "¿Está funcionando?",
    fr: "Est-ce que ça marche?",
    de: "Funktioniert es?",
    ru: "Работает ли это?",
    da: "Virker det?",
    it: "Funziona?",
    cs: "Funguje to?",
    nl: "Werkt het?",
    no: "Fungerer det?",
    pl: "Czy to działa?",
    sv: "Fungerar det?",
    tr: "Çalışıyor mu?",
    uk: "Це працює?",
    ro: "Funcționează?",
    bg: "Работи ли?",
    be: "Ці працуе?",
    fi: "Toimiiko se?",
    pt: "Está funcionando?",
    hr: "Radi li?",
    sl: "Ali deluje?",
    el: "Λειτουργεί;",
    hu: "Működik?",
    sk: "Funguje to?",
    ga: "An Oibríonn sé?",
    ja: "それは機能していますか？",
    "zh-CN": "它工作吗？",
    "zh-TW": "它工作嗎？",
    ko: "작동합니까?",
    ar: "هل هذا يعمل؟",
    ms: "Adakah Ia Berfungsi?",
    th: "มันทำงานไหม?",
    vi: "Nó có hoạt động không?",
    tl: "Kumakain ba ito?",
    id: "Apakah Ini Bekerja?",
    ur: "کیا یہ کام کر رہا ہے؟",
    fa: "آیا کار می کند؟",
    my: "ဒီအလုပ်ကိုလုပ်ပါသလား",
  },
  Yes: {
    en: "Yes",
    es: "Sí",
    fr: "Oui",
    de: "Ja",
    ru: "да",
    da: "Ja",
    it: "Sì",
    cs: "Ano",
    nl: "Ja",
    no: "Ja",
    pl: "Tak",
    sv: "Ja",
    tr: "Evet",
    uk: "Так",
    ro: "Da",
    bg: "Да",
    be: "Так",
    fi: "Kyllä",
    pt: "Sim",
    hr: "Da",
    sl: "Da",
    el: "Ναί",
    hu: "Igen",
    sk: "Áno",
    ga: "Tá",
    ja: "はい",
    "zh-CN": "是",
    "zh-TW": "是",
    ko: "예",
    ar: "نعم",
    ms: "Ya",
    th: "ใช่",
    vi: "Đúng",
    tl: "Oo",
    id: "Iya",
    ur: "جی ہاں",
    fa: "بله",
    my: "ဟုတ်ပါ",
  },
  No: {
    en: "No",
    es: "No",
    fr: "Non",
    de: "Nein",
    ru: "нет",
    da: "Ingen",
    it: "No",
    cs: "Ne",
    nl: "Nee",
    no: "Nei",
    pl: "Nie",
    sv: "Nej",
    tr: "Hayır",
    uk: "Ні",
    ro: "Nu",
    bg: "Не",
    be: "Не",
    fi: "Ei",
    pt: "Não",
    hr: "Ne",
    sl: "Ne",
    el: "Όχι",
    hu: "Nem",
    sk: "Nie",
    ga: "Níl",
    ja: "いいえ",
    "zh-CN": "没有",
    "zh-TW": "沒有",
    ko: "아니",
    ar: "لا",
    ms: "Tidak",
    th: "ไม่",
    vi: "Không",
    tl: "Hindi",
    id: "Tidak",
    ur: "نہیں",
    fa: "نه",
    my: "မဟုတ်ပါ",
  },
  AddCoupon: {
    en: "Add Coupon",
    es: "Agregar cupón",
    fr: "Ajouter un coupon",
    de: "Gutschein hinzufügen",
    ru: "Добавить купон",
    da: "Tilføj kupon",
    it: "Aggiungi coupon",
    cs: "Přidat kupón",
    nl: "Coupon toevoegen",
    no: "Legg til kupong",
    pl: "Dodaj kupon",
    sv: "Lägg till kupong",
    tr: "Kupon Ekle",
    uk: "Додати купон",
    ro: "Adăugați cupon",
    bg: "Добавете купон",
    be: "Дадаць купон",
    fi: "Lisää kuponki",
    pt: "Adicionar cupom",
    hr: "Dodaj kupon",
    sl: "Dodaj kupon",
    el: "Προσθέστε κουπόνι",
    hu: "Kupon hozzáadása",
    sk: "Pridať kupón",
    ga: "Cuir Cupán leis",
    ja: "クーポンを追加",
    "zh-CN": "添加优惠券",
    "zh-TW": "添加優惠券",
    ko: "쿠폰 추가",
    ar: "أضف كوبون",
    ms: "Tambah Kupon",
    th: "เพิ่มคูปอง",
    vi: "Thêm phiếu giảm giá",
    tl: "Magdagdag ng Kupon",
    id: "Tambahkan Kupon",
    ur: "کوپن شامل کریں",
    fa: "کوپن اضافه کنید",
    my: "ကူပွန်တင်ပါ",
  },
  TotalOffers: {
    en: "Total Offers",
    es: "Ofertas totales",
    fr: "Offres totales",
    de: "Gesamtangebote",
    ru: "Всего предложений",
    da: "Samlede tilbud",
    it: "Offerte totali",
    cs: "Celkem nabídek",
    nl: "Totale aanbiedingen",
    no: "Totalt tilbud",
    pl: "Wszystkie oferty",
    sv: "Totala erbjudanden",
    tr: "Toplam Teklifler",
    uk: "Всього пропозицій",
    ro: "Oferte totale",
    bg: "Общи предложения",
    be: "Усяго прапановаў",
    fi: "Kaikki tarjoukset",
    pt: "Ofertas totais",
    hr: "Ukupne ponude",
    sl: "Skupne ponudbe",
    el: "Συνολικές προσφορές",
    hu: "Összes ajánlat",
    sk: "Celkové ponuky",
    ga: "Iomlán Tairiscintí",
    ja: "合計オファー",
    "zh-CN": "总报价",
    "zh-TW": "總報價",
    ko: "총 제공",
    ar: "مجموع العروض",
    ms: "Jumlah Tawaran",
    th: "ข้อเสนอทั้งหมด",
    vi: "Tổng số ưu đãi",
    tl: "Kabuuang Alo",
    id: "Total Penawaran",
    ur: "کل پیشکشیں",
    fa: "کل پیشنهادات",
    my: "စုစုပေါင်းအမျိုးအစား",
  },
  SitewideOffers: {
    en: "Sitewide Offers",
    es: "Ofertas de toda la web",
    fr: "Offres sur tout le site",
    de: "Angebote auf der ganzen Website",
    ru: "Предложения на всем сайте",
    da: "Webstedstilbud",
    it: "Offerte su tutto il sito",
    cs: "Nabídky na celém webu",
    nl: "Websitebrede aanbiedingen",
    no: "Nettstedstilbud",
    pl: "Oferty na stronie",
    sv: "Webbplatserbjudanden",
    tr: "Site Genel Teklifler",
    uk: "Пропозиції на всьому сайті",
    ro: "Oferte pe întregul site",
    bg: "Оферти за целия сайт",
    be: "Прапановы на ўсёй старонцы",
    fi: "Sivustokohtaiset tarjoukset",
    pt: "Ofertas em todo o site",
    hr: "Ponude na cijelom web mjestu",
    sl: "Ponudbe na celotnem spletnem mestu",
    el: "Προσφορές σε όλο τον ιστότοπο",
    hu: "Webhelyi ajánlatok",
    sk: "Ponuky na celom webe",
    ga: "Ofáltaí ar fud an láithreáin",
    ja: "サイト全体のオファー",
    "zh-CN": "整站优惠",
    "zh-TW": "整站優惠",
    ko: "사이트 전체 제공",
    ar: "عروض على مستوى الموقع",
    ms: "Tawaran Situs",
    th: "ข้อเสนอทั่วไป",
    vi: "Ưu đãi trên toàn trang",
    tl: "Mga Alo sa Buong Site",
    id: "Penawaran Situs",
    ur: "سائٹ وائیڈ پیشکشیں",
    fa: "پیشنهادات سایت",
    my: "ဆိုက်အားလုံးအမျိုးအစား",
  },
  BestDiscount: {
    en: "Best Discount",
    es: "Mejor descuento",
    fr: "Meilleure remise",
    de: "Bester Rabatt",
    ru: "Лучшая скидка",
    da: "Bedste rabat",
    it: "Miglior sconto",
    cs: "Nejlepší sleva",
    nl: "Beste korting",
    no: "Beste rabatt",
    pl: "Najlepsza zniżka",
    sv: "Bästa rabatt",
    tr: "En İyi İndirim",
    uk: "Краща знижка",
    ro: "Cel mai bun discount",
    bg: "Най-добрата отстъпка",
    be: "Лепшая зніжка",
    fi: "Paras alennus",
    pt: "Melhor desconto",
    hr: "Najbolji popust",
    sl: "Najboljši popust",
    el: "Καλύτερη έκπτωση",
    hu: "Legjobb kedvezmény",
    sk: "Najlepšia zľava",
    ga: "An Leid is Fearr",
    ja: "最高の割引",
    "zh-CN": "最佳折扣",
    "zh-TW": "最佳折扣",
    ko: "최고의 할인",
    ar: "أفضل خصم",
    ms: "Diskaun Terbaik",
    th: "ส่วนลดที่ดีที่สุด",
    vi: "Giảm giá tốt nhất",
    tl: "Pinakamahusay na Diskwento",
    id: "Diskon Terbaik",
    ur: "بہترین ڈسکاؤنٹ",
    fa: "بهترین تخفیف",
    my: "အမြင့်ဆုံးလျှောက်",
  },
  ViewAllStores: {
    en: "View All Stores",
    es: "Ver todas las tiendas",
    fr: "Voir tous les magasins",
    de: "Alle Geschäfte anzeigen",
    ru: "Просмотреть все магазины",
    da: "Se alle butikker",
    it: "Visualizza tutti i negozi",
    cs: "Zobrazit všechny obchody",
    nl: "Bekijk alle winkels",
    no: "Vis alle butikker",
    pl: "Wyświetl wszystkie sklepy",
    sv: "Visa alla butiker",
    tr: "Tüm Mağazaları Görüntüle",
    uk: "Переглянути всі магазини",
    ro: "Vizualizați toate magazinele",
    bg: "Преглед на всички магазини",
    be: "Прагляд усіх магазінаў",
    fi: "Näytä kaikki kaupat",
    pt: "Ver todas as lojas",
    hr: "Prikaži sve trgovine",
    sl: "Ogled vseh trgovin",
    el: "Προβολή όλων των καταστημάτων",
    hu: "Az összes üzlet megtekintése",
    sk: "Zobraziť všetky obchody",
    ga: "Féach ar gach siopa",
    ja: "すべての店舗を表示",
    "zh-CN": "查看所有商店",
    "zh-TW": "查看所有商店",
    ko: "모든 상점보기",
    ar: "عرض جميع المتاجر",
    ms: "Lihat Semua Kedai",
    th: "ดูร้านค้าทั้งหมด",
    vi: "Xem tất cả cửa hàng",
    tl: "Tingnan ang Lahat ng Tindahan",
    id: "Lihat Semua Toko",
    ur: "تمام اسٹورز دیکھیں",
    fa: "مشاهده همه فروشگاه ها",
    my: "ဆိုက်အားလုံးကြည့်ပါ",
  },
  ViewMore: {
    en: "View More",
    es: "Ver más",
    fr: "Voir plus",
    de: "Mehr anzeigen",
    ru: "Посмотреть больше",
    da: "Se mere",
    it: "Vedi di più",
    cs: "Zobrazit více",
    nl: "Bekijk meer",
    no: "Se mer",
    pl: "Zobacz więcej",
    sv: "Visa mer",
    tr: "Daha fazla görüntüle",
    uk: "Переглянути більше",
    ro: "Vezi mai mult",
    bg: "Виж повече",
    be: "Праглядзець больш",
    fi: "Näytä lisää",
    pt: "Ver mais",
    hr: "Prikaži više",
    sl: "Prikaži več",
    el: "Δείτε περισσότερα",
    hu: "További megtekintése",
    sk: "Zobraziť viac",
    ga: "Féach Níos Mó",
    ja: "もっと見る",
    "zh-CN": "查看更多",
    "zh-TW": "查看更多",
    ko: "더보기",
    ar: "عرض المزيد",
    ms: "Lihat lebih banyak",
    th: "ดูเพิ่มเติม",
    vi: "Xem thêm",
    tl: "Tingnan ang higit pa",
    id: "Lihat Lebih Banyak",
    ur: "مزید دیکھیں",
    fa: "بیشتر ببینید",
    my: "ပိုမိုကြည့်ပါ",
  },
  PopularStores: {
    en: "Popular Stores",
    es: "Tiendas populares",
    fr: "Magasins populaires",
    de: "Beliebte Geschäfte",
    ru: "Популярные магазины",
    da: "Populære butikker",
    it: "Negozi popolari",
    cs: "Oblíbené obchody",
    nl: "Populaire winkels",
    no: "Populære butikker",
    pl: "Popularne sklepy",
    sv: "Populära butiker",
    tr: "Popüler Mağazalar",
    uk: "Популярні магазини",
    ro: "Magazine populare",
    bg: "Популярни магазини",
    be: "Папулярныя магазіны",
    fi: "Suositut kaupat",
    pt: "Lojas populares",
    hr: "Popularne trgovine",
    sl: "Priljubljene trgovine",
    el: "Δημοφιλή καταστήματα",
    hu: "Népszerű üzletek",
    sk: "Obľúbené obchody",
    ga: "Siopaí Coitianta",
    ja: "人気の店舗",
    "zh-CN": "热门商店",
    "zh-TW": "熱門商店",
    ko: "인기 상점",
    ar: "المتاجر الشهيرة",
    ms: "Kedai Popular",
    th: "ร้านค้ายอดนิยม",
    vi: "Cửa hàng phổ biến",
    tl: "Mga Sikat na Tindahan",
    id: "Toko Populer",
    ur: "مقبول اسٹورز",
    fa: "فروشگاه های محبوب",
    my: "အများဆုံးဆိုက်များ",
  },
  OffersFromSimilarStores: {
    en: "Offers From Similar Stores",
    es: "Ofertas de tiendas similares",
    fr: "Offres de magasins similaires",
    de: "Angebote von ähnlichen Geschäften",
    ru: "Предложения от похожих магазинов",
    da: "Tilbud fra lignende butikker",
    it: "Offerte da negozi simili",
    cs: "Nabídky od podobných obchodů",
    nl: "Aanbiedingen van vergelijkbare winkels",
    no: "Tilbud fra lignende butikker",
    pl: "Oferty od podobnych sklepów",
    sv: "Erbjudanden från liknande butiker",
    tr: "Benzer Mağazalardan Teklifler",
    uk: "Пропозиції від схожих магазинів",
    ro: "Oferte de la magazine similare",
    bg: "Предложения от подобни магазини",
    be: "Прапановы ад падобных магазінаў",
    fi: "Tarjoukset samankaltaisista kaupoista",
    pt: "Ofertas de lojas semelhantes",
    hr: "Ponude iz sličnih trgovina",
    sl: "Ponudbe iz podobnih trgovin",
    el: "Προσφορές από παρόμοια καταστήματα",
    hu: "Ajánlatok hasonló üzletekből",
    sk: "Ponuky od podobných obchodov",
    ga: "Ofáltaí ó Siopaí Cosúil",
    ja: "類似店舗からのオファー",
    "zh-CN": "类似商店的优惠",
    "zh-TW": "類似商店的優惠",
    ko: "유사한 상점의 제안",
    ar: "عروض من متاجر مماثلة",
    ms: "Tawaran Dari Kedai Yang Sama",
    th: "ข้อเสนอจากร้านค้าที่คล้ายกัน",
    vi: "Ưu đãi từ các cửa hàng tương tự",
    tl: "Mga Alo Mula sa Katulad na Mga Tindahan",
    id: "Penawaran Dari Toko Serupa",
    ur: "مماثل اسٹورز سے پیشکشیں",
    fa: "پیشنهادات از فروشگاه های مشابه",
    my: "ဆိုက်တစ်ခုမှရှိသောအမျိုးအစား",
  },

  SHOWCODE: {
    en: "SHOW CODE",
    es: "MOSTRAR CÓDIGO",
    fr: "AFFICHER LE CODE",
    de: "CODE ANZEIGEN",
    ru: "ПОКАЗАТЬ КОД",
    da: "VIS KODE",
    it: "MOSTRA CODICE",
    cs: "UKÁZAT KÓD",
    nl: "CODE WEERGEVEN",
    no: "VIS KODE",
    pl: "POKAŻ KOD",
    sv: "VISA KOD",
    tr: "KODU GÖSTER",
    uk: "ПОКАЗАТИ КОД",
    ro: "ARATA COD",
    bg: "ПОКАЖИ КОД",
    be: "ПАКАЗАЦЬ КОД",
    fi: "NÄYTÄ KOODI",
    pt: "MOSTRAR CÓDIGO",
    hr: "PRIKAŽI KOD",
    sl: "PRIKAŽI KODO",
    el: "ΕΜΦΑΝΙΣΗ ΚΩΔΙΚΑ",
    hu: "KÓD MEGJELENÍTÉSE",
    sk: "ZOBRAZIŤ KÓD",
    ga: "TAISPEÁIN CÓD",
    ja: "コードを表示",
    "zh-CN": "显示代码",
    "zh-TW": "顯示代碼",
    ko: "코드 표시",
    ar: "عرض الكود",
    ms: "TUNJUKKAN KOD",
    th: "แสดงรหัส",
    vi: "HIỂN THỊ MÃ",
    tl: "IPAKITA ANG KODE",
    id: "TAMPILKAN KODE",
    ur: "کوڈ دکھائیں",
    fa: "نمایش کد",
    my: "ကုဒ်ကိုပြပါ",
  },
  VIEWDEAL: {
    en: "VIEW DEAL",
    es: "VER OFERTA",
    fr: "VOIR L'OFFRE",
    de: "DEAL ANZEIGEN",
    ru: "ПОСМОТРЕТЬ СДЕЛКУ",
    da: "SE AFTALE",
    it: "VEDI OFFERTA",
    cs: "ZOBRAZIT DEAL",
    nl: "BEKIJK DEAL",
    no: "SE AVTALE",
    pl: "WIDOK OFERTA",
    sv: "VISA ERBJUDANDE",
    tr: "DEAL GÖRÜNTÜLE",
    uk: "ПОКАЗАТИ УГОДУ",
    ro: "VEZI OFERTA",
    bg: "ВИЖ СДЕЛКА",
    be: "ПАКАЗАЦЬ УГОДУ",
    fi: "NÄYTÄ TARJOUS",
    pt: "VER OFERTA",
    hr: "PRIKAŽI PONUDU",
    sl: "POGLEJTE PONUDBO",
    el: "ΔΕΙΤΕ ΠΡΟΣΦΟΡΑ",
    hu: "AJÁNLAT MEGTEKINTÉSE",
    sk: "ZOBRAZIŤ DEAL",
    ga: "FÉACH AR AN RÁTA",
    ja: "ディールを表示",
    "zh-CN": "查看交易",
    "zh-TW": "查看交易",
    ko: "딜 보기",
    ar: "عرض الصفقة",
    ms: "LIHAT URUSAN",
    th: "ดูดีล",
    vi: "XEM GIAO DỊCH",
    tl: "TINGNAN ANG DEAL",
    id: "LIHAT PENAWARAN",
    ur: "ڈیل دیکھیں",
    fa: "معامله را مشاهده کنید",
    my: "အစားထိုးကြည့်ပါ",
  },
  GoToStore: {
    en: "Go to Store",
    es: "Ir a la tienda",
    fr: "Aller au magasin",
    de: "Zum Laden gehen",
    ru: "Перейти в магазин",
    da: "Gå til butik",
    it: "Vai al negozio",
    cs: "Jít do obchodu",
    nl: "Ga naar winkel",
    no: "Gå til butikk",
    pl: "Idź do sklepu",
    sv: "Gå till butik",
    tr: "Mağazaya git",
    uk: "Перейти в магазин",
    ro: "Du-te la magazin",
    bg: "Отиди в магазина",
    be: "Пераходзіце ў магазін",
    fi: "Mene kauppaan",
    pt: "Ir para a loja",
    hr: "Idi u trgovinu",
    sl: "Pojdi v trgovino",
    el: "Πήγαινε στο κατάστημα",
    hu: "Menj a boltba",
    sk: "Ísť do obchodu",
    ga: "Téigh go dtí an siopa",
    ja: "ストアに行く",
    "zh-CN": "去商店",
    "zh-TW": "去商店",
    ko: "상점으로 가기",
    ar: "اذهب إلى المتجر",
    ms: "Pergi ke kedai",
    th: "ไปที่ร้าน",
    vi: "Đi đến cửa hàng",
    tl: "Pumunta sa Tindahan",
    id: "Pergi ke Toko",
    ur: "اسٹور پر جائیں",
    fa: "به فروشگاه برو",
    my: "ဆိုက်သို့သွားပါ",
  },
  LimitedTime: {
    en: "Limited Time",
    es: "Tiempo limitado",
    fr: "Temps limité",
    de: "Begrenzte Zeit",
    ru: "Ограниченное время",
    da: "Begrænset tid",
    it: "Tempo limitato",
    cs: "Omezený čas",
    nl: "Beperkte tijd",
    no: "Begrenset tid",
    pl: "Ograniczony czas",
    sv: "Begränsad tid",
    tr: "Sınırlı Zaman",
    uk: "Обмежений час",
    ro: "Timp limitat",
    bg: "Ограничено време",
    be: "Абмежаваны час",
    fi: "Rajoitettu aika",
    pt: "Tempo limitado",
    hr: "Ograničeno vrijeme",
    sl: "Omejen čas",
    el: "Περιορισμένος χρόνος",
    hu: "Korlátozott idő",
    sk: "Obmedzený čas",
    ga: "Am Sínithe",
    ja: "制限時間",
    "zh-CN": "有限时间",
    "zh-TW": "有限時間",
    ko: "제한 시간",
    ar: "وقت محدود",
    ms: "Masa Terhad",
    th: "เวลาจำกัด",
    vi: "Thời Gian Giới Hạn",
    tl: "Limitadong Oras",
    id: "Waktu Terbatas",
    ur: "محدود وقت",
    fa: "زمان محدود",
    my: "ကိုယ်တိုင်အချိန်",
  },
  Step: {
    en: "Step",
    es: "Paso",
    fr: "Étape",
    de: "Schritt",
    ru: "Шаг",
    da: "Trin",
    it: "Passo",
    cs: "Krok",
    nl: "Stap",
    no: "Trinn",
    pl: "Krok",
    sv: "Steg",
    tr: "Adım",
    uk: "Крок",
    ro: "Pas",
    bg: "Стъпка",
    be: "Крок",
    fi: "Askel",
    pt: "Passo",
    hr: "Korak",
    sl: "Korak",
    el: "Βήμα",
    hu: "Lépés",
    sk: "Krok",
    ga: "Céim",
    ja: "ステップ",
    "zh-CN": "步",
    "zh-TW": "步",
    ko: "단계",
    ar: "خطوة",
    ms: "Langkah",
    th: "ขั้นตอน",
    vi: "Bước",
    tl: "Hakbang",
    id: "Langkah",
    ur: "قدم",
    fa: "قدم",
    my: "အဆင့်",
  },
  ApplyCoupon: {
    en: "Apply Coupon",
    es: "Aplicar cupón",
    fr: "Appliquer le coupon",
    de: "Gutschein anwenden",
    ru: "Применить купон",
    da: "Anvend kupon",
    it: "Applica coupon",
    cs: "Použít kupón",
    nl: "Coupon toepassen",
    no: "Bruk kupong",
    pl: "Zastosuj kupon",
    sv: "Använd kupong",
    tr: "Kupon Uygula",
    uk: "Застосувати купон",
    ro: "Aplică cupon",
    bg: "Приложете купон",
    be: "Прымяніце купон",
    fi: "Käytä kuponkia",
    pt: "Aplicar cupom",
    hr: "Primijeni kupon",
    sl: "Uporabi kupon",
    el: "Εφαρμογή κουπονιού",
    hu: "Kupon alkalmazása",
    sk: "Použiť kupón",
    ga: "Iarratas Cúipéin",
    ja: "クーポンを適用",
    "zh-CN": "应用优惠券",
    "zh-TW": "應用優惠券",
    ko: "쿠폰 적용",
    ar: "تطبيق القسيمة",
    ms: "Memohon Kupon",
    th: "ใช้คูปอง",
    vi: "Áp dụng phiếu giảm giá",
    tl: "Mag-apply ng Kupon",
    id: "Terapkan Kupon",
    ur: "کوپن لگائیں",
    fa: "کوپن اعمال کریں",
    my: "ကုတ်လုပ်ပါ",
  },
  viewsLastWeek: {
    en: "views last week",
    es: "vistas la semana pasada",
    fr: "vues la semaine dernière",
    de: "Ansichten letzte Woche",
    ru: "просмотры на прошлой неделе",
    da: "visninger sidste uge",
    it: "visualizzazioni la scorsa settimana",
    cs: "zobrazení minulý týden",
    nl: "weergaven vorige week",
    no: "visninger forrige uke",
    pl: "wyświetlenia w zeszłym tygodniu",
    sv: "visningar förra veckan",
    tr: "geçen hafta görüntülemeler",
    uk: "перегляди минулого тижня",
    ro: "vizualizări săptămâna trecută",
    bg: "гледания миналата седмица",
    be: "прагляды на мінулым тыдні",
    fi: "näkymät viime viikolla",
    pt: "visualizações na semana passada",
    hr: "prikazi prošlog tjedna",
    sl: "prikazi prejšnji teden",
    el: "προβολές την προηγούμενη εβδομάδα",
    hu: "megtekintések múlt héten",
    sk: "zobrazenia minulý týždeň",
    ga: "tuairimí an tseachtain seo caite",
    ja: "先週のビュー",
    "zh-CN": "上周观看",
    "zh-TW": "上週觀看",
    ko: "지난 주 조회수",
    ar: "الآراء الأسبوع الماضي",
    ms: "pandangan minggu lalu",
    th: "มุมมองในสัปดาห์ที่แล้ว",
    vi: "lượt xem tuần trước",
    tl: "mga pananaw noong nakaraang linggo",
    id: "tampilan minggu lalu",
    ur: "پچھلے ہفتے کی نظریں",
    fa: "نمایش های هفته گذشته",
    my: "ပြီးဆုံးအပ်ဒိတ်များ",
  },
  ViewOffers: {
    en: "View Offers",
    es: "Ver ofertas",
    fr: "Voir les offres",
    de: "Angebote anzeigen",
    ru: "Посмотреть предложения",
    da: "Se tilbud",
    it: "Visualizza offerte",
    cs: "Zobrazit nabídky",
    nl: "Bekijk aanbiedingen",
    no: "Se tilbud",
    pl: "Zobacz oferty",
    sv: "Visa erbjudanden",
    tr: "Teklifleri Görüntüle",
    uk: "Переглянути пропозиції",
    ro: "Vezi oferte",
    bg: "Вижте оферти",
    be: "Праглядзець прапановы",
    fi: "Näytä tarjoukset",
    pt: "Ver ofertas",
    hr: "Prikaži ponude",
    sl: "Ogled ponudb",
    el: "Προβολή προσφορών",
    hu: "Ajánlatok megtekintése",
    sk: "Zobraziť ponuky",
    ga: "Féach ar Ofáltaí",
    ja: "オファーを表示",
    "zh-CN": "查看优惠",
    "zh-TW": "查看優惠",
    ko: "제안보기",
    ar: "عرض العروض",
    ms: "Lihat Tawaran",
    th: "ดูข้อเสนอ",
    vi: "Xem Ưu đãi",
    tl: "Tingnan ang Alo",
    id: "Lihat Penawaran",
    ur: "پیشکشیں دیکھیں",
    fa: "مشاهده پیشنهادات",
    my: "အများဆုံးကြည့်ပါ",
  },
  ViewAll: {
    en: "View All",
    es: "Ver todo",
    fr: "Voir tout",
    de: "Alle anzeigen",
    ru: "Посмотреть все",
    da: "Se alt",
    it: "Visualizza tutto",
    cs: "Zobrazit vše",
    nl: "Alles bekijken",
    no: "Se alt",
    pl: "Zobacz wszystko",
    sv: "Visa allt",
    tr: "Hepsini Gör",
    uk: "Показати все",
    ro: "Vezi tot",
    bg: "Виж всичко",
    be: "Праглядзець усё",
    fi: "Näytä kaikki",
    pt: "Ver tudo",
    hr: "Prikaži sve",
    sl: "Ogled vsega",
    el: "Δείτε όλα",
    hu: "Összes megtekintése",
    sk: "Zobraziť všetko",
    ga: "Féach ar Gach",
    ja: "すべてを表示",
    "zh-CN": "查看全部",
    "zh-TW": "查看全部",
    ko: "모두보기",
    ar: "عرض الكل",
    ms: "Lihat Semua",
    th: "ดูทั้งหมด",
    vi: "Xem tất cả",
    tl: "Tingnan Lahat",
    id: "Lihat Semua",
    ur: "سب دیکھیں",
    fa: "همه را ببینید",
    my: "အားလုံးကြည့်ပါ",
  },
  SimilarCoupons: {
    en: "Similar Coupons",
    es: "Cupones similares",
    fr: "Coupons similaires",
    de: "Ähnliche Gutscheine",
    ru: "Похожие купоны",
    da: "Lignende kuponer",
    it: "Coupon simili",
    cs: "Podobné kupóny",
    nl: "Vergelijkbare coupons",
    no: "Lignende kuponger",
    pl: "Podobne kupony",
    sv: "Liknande kuponger",
    tr: "Benzer Kuponlar",
    uk: "Схожі купони",
    ro: "Cupoane similare",
    bg: "Подобни купони",
    be: "Падобныя купоны",
    fi: "Samanlaiset kuponit",
    pt: "Cupons semelhantes",
    hr: "Slični kuponi",
    sl: "Podobni kuponi",
    el: "Παρόμοια κουπόνια",
    hu: "Hasonló kuponok",
    sk: "Podobné kupóny",
    ga: "Cupóin Cosúil",
    ja: "類似クーポン",
    "zh-CN": "类似优惠券",
    "zh-TW": "類似優惠券",
    ko: "유사한 쿠폰",
    ar: "كوبونات مماثلة",
    ms: "Kupon Serupa",
    th: "คูปองที่คล้ายกัน",
    vi: "Mã giảm giá tương tự",
    tl: "Katulad na Mga Kupon",
    id: "Kupon Serupa",
    ur: "مشابہ کوپن",
    fa: "کوپن های مشابه",
    my: "အများဆုံးကုဒ်များ",
  },
  SimilarStoresYouMayLike: {
    en: "Similar Stores You May Like",
    es: "Tiendas similares que te pueden gustar",
    fr: "Magasins similaires que vous pourriez aimer",
    de: "Ähnliche Geschäfte, die Ihnen gefallen könnten",
    ru: "Похожие магазины, которые вам могут понравиться",
    da: "Lignende butikker, du måske kan lide",
    it: "Negozi simili che potrebbero piacerti",
    cs: "Podobné obchody, které by se vám mohly líbit",
    nl: "Vergelijkbare winkels die je misschien leuk vindt",
    no: "Lignende butikker du kanskje liker",
    pl: "Podobne sklepy, które mogą Ci się spodobać",
    sv: "Liknande butiker du kanske gillar",
    tr: "Hoşunuza gidebilecek benzer mağazalar",
    uk: "Схожі магазини, які вам можуть сподобатися",
    ro: "Magazine similare care v-ar putea plăcea",
    bg: "Подобни магазини, които бихте могли харесате",
    be: "Падобныя магазіны, які вам могуць падабацца",
    fi: "Samanlaiset kaupat, jotka saattavat kiinnostaa sinua",
    pt: "Lojas semelhantes que você pode gostar",
    hr: "Slične trgovine koje bi vam se mogle svidjeti",
    sl: "Podobne trgovine, ki bi vam bile všeč",
    el: "Παρόμοια καταστήματα που ίσως σας αρέσουν",
    hu: "Hasonló üzletek, amelyek tetszhetnek",
    sk: "Podobné obchody, ktoré by sa vám mohli páčiť",
    ga: "Siopaí Cosúil a d'fhéadfadh a bheith agat",
    ja: "お気に入りの類似ストア",
    "zh-CN": "您可能喜欢的类似商店",
    "zh-TW": "您可能喜歡的類似商店",
    ko: "좋아할 수 있는 유사한 상점",
    ar: "المتاجر المماثلة التي قد ت عجبك",
    ms: "Kedai Serupa Yang Anda Mungkin Suka",
    th: "ร้านค้าที่คล้ายกันที่คุณอาจชอบ",
    vi: "Cửa Hàng Tương Tự Bạn Có Thể Thích",
    tl: "Mga Katulad na Tindahan na Maaaring Gustuhin Mo",
    id: "Toko Serupa yang Mungkin Anda Suka",
    ur: "مماثل اسٹور جو آپ کو پسند آ سکتے ہیں",
    fa: "فروشگاه های مشابه که ممکن است دوست داشته باشید",
    my: "သင်ခွင့်ပြုရန်အသေးစိတ်များ",
  },
  StoreStats: {
    en: "Store Stats",
    es: "Estadísticas de la tienda",
    fr: "Statistiques du magasin",
    de: "Shop-Statistiken",
    ru: "Статистика магазина",
    da: "Butikstatistik",
    it: "Statistiche del negozio",
    cs: "Statistiky obchodu",
    nl: "Winkelstatistieken",
    no: "Butikkstatistikk",
    pl: "Statystyki sklepu",
    sv: "Butikstatistik",
    tr: "Mağaza İstatistikleri",
    uk: "Статистика магазину",
    ro: "Statistici magazin",
    bg: "Статистика на магазина",
    be: "Статыстыка магазіна",
    fi: "Kaupan tilastot",
    pt: "Estatísticas da loja",
    hr: "Statistika trgovine",
    sl: "Statistika trgovine",
    el: "Στατιστικά καταστήματος",
    hu: "Áruház statisztika",
    sk: "Štatistiky obchodu",
    ga: "Staitisticí Siopa",
    ja: "ストア統計",
    "zh-CN": "商店统计",
    "zh-TW": "商店統計",
    ko: "상점 통계",
    ar: "إحصائيات المتجر",
    ms: "Statistik Kedai",
    th: "สถิติร้านค้า",
    vi: "Thống kê Cửa hàng",
    tl: "Estadistika ng Tindahan",
    id: "Statistik Toko",
    ur: "اسٹور کی اعداد و شمار",
    fa: "آمار فروشگاه",
    my: "ဆိုက်စာရင်း",
  },
  Verified: {
    en: "Verified",
    es: "Verificado",
    fr: "Vérifié",
    de: "Verifiziert",
    ru: "Проверенный",
    da: "Bekræftet",
    it: "Verificato",
    cs: "Ověřeno",
    nl: "Geverifieerd",
    no: "Verifisert",
    pl: "Zweryfikowany",
    sv: "Verifierad",
    tr: "Doğrulandı",
    uk: "Перевірено",
    ro: "Verificat",
    bg: "Проверен",
    be: "Правераны",
    fi: "Vahvistettu",
    pt: "Verificado",
    hr: "Provjereno",
    sl: "Preverjeno",
    el: "Επαληθευμένο",
    hu: "Ellenőrzött",
    sk: "Overené",
    ga: "Dearbhaithe",
    ja: "確認済み",
    "zh-CN": "已验证",
    "zh-TW": "已驗證",
    ko: "확인 됨",
    ar: "تم التحقق",
    ms: "Disahkan",
    th: "ได้รับการยืนยัน",
    vi: "Đã Xác minh",
    tl: "Napatunayan",
    id: "Terverifikasi",
    ur: "تصدیق شدہ",
    fa: "تایید شده",
    my: "အတည်ပြုပြီး",
  },
  Off: {
    en: "Off",
    es: "de descuento",
    fr: "de réduction",
    de: "Rabatt",
    ru: "скидка",
    da: "rabat",
    it: "di sconto",
    cs: "sleva",
    nl: "korting",
    no: "rabatt",
    pl: "zniżki",
    sv: "rabatt",
    tr: "indirim",
    uk: "знижка",
    ro: "reducere",
    bg: "отстъпка",
    be: "зніжка",
    fi: "alennus",
    pt: "de desconto",
    hr: "popusta",
    sl: "popust",
    el: "έκπτωση",
    hu: "kedvezmény",
    sk: "zľava",
    ga: "Oifig",
    ja: "オフ",
    "zh-CN": "折扣",
    "zh-TW": "折扣",
    ko: "할인",
    ar: "خصم",
    ms: "Diskaun",
    th: "ส่วนลด",
    vi: "Giảm giá",
    tl: "Bawas",
    id: "Diskon",
    ur: "چھوٹ",
    fa: "تخفیف",
    my: "လျှပ်စစ်",
  },
  NoStoresFound: {
    en: "No Stores Found",
    es: "No se encontraron tiendas",
    fr: "Aucun magasin trouvé",
    de: "Keine Geschäfte gefunden",
    ru: "Магазины не найдены",
    da: "Ingen butikker fundet",
    it: "Nessun negozio trovato",
    cs: "Nebyly nalezeny žádné obchody",
    nl: "Geen winkels gevonden",
    no: "Ingen butikker funnet",
    pl: "Nie znaleziono sklepów",
    sv: "Inga butiker hittades",
    tr: "Mağaza Bulunamadı",
    uk: "Магазини не знайдено",
    ro: "Niciun magazin găsit",
    bg: "Не са намерени магазини",
    be: "Магазіны не знойдзены",
    fi: "Ei löydetty kauppoja",
    pt: "Nenhuma loja encontrada",
    hr: "Nisu pronađene trgovine",
    sl: "Ni najdenih trgovin",
    el: "Δεν βρέθηκαν καταστήματα",
    hu: "Nem található üzlet",
    sk: "Nenašli sa žiadne obchody",
    ga: "Níor aimsíodh aon siopa",
    ja: "店舗が見つかりません",
    "zh-CN": "未找到商店",
    "zh-TW": "未找到商店",
    ko: "상점을 찾을 수 없습니다",
    ar: "لم يتم العثور على متاجر",
    ms: "Tiada Kedai Dijumpai",
    th: "ไม่พบร้านค้า",
    vi: "Không Tìm Thấy Cửa Hàng",
    tl: "Walang Mga Tindahan na Natagpuan",
    id: "Tidak Ada Toko Ditemukan",
    ur: "کوئی اسٹورز نہیں ملے",
    fa: "هیچ فروشگاهی یافت نشد",
    my: "ဆိုက်မရှိပါဘူး",
  },
  CouponUsageHistory: {
    en: "Coupon Usage History",
    es: "Historial de uso del cupón",
    fr: "Historique d'utilisation du coupon",
    de: "Gutscheinverlauf",
    ru: "История использования купона",
    da: "Kuponbrugshistorik",
    it: "Cronologia dell'uso del coupon",
    cs: "Historie použití kupónu",
    nl: "Coupongebruiksgeschiedenis",
    no: "Kupongbrukshistorikk",
    pl: "Historia użycia kuponu",
    sv: "Kuponganvändningshistorik",
    tr: "Kupon Kullanım Geçmişi",
    uk: "Історія використання купона",
    ro: "Istoricul utilizării cuponului",
    bg: "История на използване на купона",
    be: "Гісторыя выкарыстання купона",
    fi: "Kupongin käyttöhistoria",
    pt: "Histórico de uso do cupom",
    hr: "Povijest korištenja kupona",
    sl: "Zgodovina uporabe kupona",
    el: "Ιστορικό χρήσης κουπονιού",
    hu: "Kuponhasználati előzmények",
    sk: "História používania kupónu",
    ga: "Stair Úsáide an Chúipéin",
    ja: "クーポン使用履歴",
    "zh-CN": "优惠券使用历史",
    "zh-TW": "優惠券使用歷史",
    ko: "쿠폰 사용 내역",
    ar: "تاريخ استخدام القسيمة",
    ms: "Sejarah Penggunaan Kupon",
    th: "ประวัติการใช้คูปอง",
    vi: "Lịch Sử Sử Dụng Mã Giảm Giá",
    tl: "Kasaysayan ng Paggamit ng Kupon",
    id: "Riwayat Penggunaan Kupon",
    ur: "کوپن کا استعمال کرنے کی تاریخ",
    fa: "تاریخچه استفاده از کوپن",
    my: "ကုတ်သုံးသမ္မတ",
  },
  AShopperMarkedTheOffer: {
    en: "A Shopper marked the offer ",
    es: "Un comprador marcó la oferta ",
    fr: "Un acheteur a marqué l'offre ",
    de: "Ein Käufer markierte das Angebot ",
    ru: "Покупатель пометил предложение ",
    da: "En shopper markerede tilbuddet ",
    it: "Un acquirente ha contrassegnato l'offerta ",
    cs: "Nákupčí označil nabídku ",
    nl: "Een shopper markeerde het aanbod ",
    no: "En shopper markerte tilbudet ",
    pl: "Kupujący oznaczył ofertę ",
    sv: "En Shopper markerade erbjudandet ",
    tr: "Bir alıcı teklifi işaretledi ",
    uk: "Покупець позначив пропозицію ",
    ro: "Un cumpărător a marcat oferta ",
    bg: "Купувачът маркира предложението ",
    be: "Пакупец пазначыў прапанову ",
    fi: "Shopper merkitsi tarjouksen ",
    pt: "Um comprador marcou a oferta ",
    hr: "Kupac je označio ponudu ",
    sl: "Kupca je označil ponudbo ",
    el: "Ένας αγοραστής σήμανε την προσφορά ",
    hu: "Egy vásárló jelölte a kínálatot ",
    sk: "Kupujúci označil ponuku ",
    ga: "Mharcóir an tairiscint ",
    ja: "ショッパーがオファーをマークしました ",
    "zh-CN": "购物者标记了优惠 ",
    "zh-TW": "購物者標記了優惠 ",
    ko: "쇼퍼가 제공을 표시했습니다 ",
    ar: "علام المتسوق العرض ",
    ms: "Pembeli menandakan tawaran ",
    th: "ผู้ช้อปปิ้งมาร์คเสนอ ",
    vi: "Người mua đã đánh dấu ưu đãi ",
    tl: "Isang Shopper ang nagmarka ng alok ",
    id: "Pembeli menandai penawaran ",
    ur: "ایک خریدار نے پیشکش کو نشان زد کیا ",
    fa: "یک خریدار پیشنهاد را علامت گذاری کرد ",
    my: "အသိပေးသူကိုအပ်ဒိတ်ပြုလုပ်ခဲ့သည် ",
  },
  asWorking: {
    en: "as Working",
    es: "como Trabajando",
    fr: "comme Travailler",
    de: "als Arbeiten",
    ru: "как Работает",
    da: "som Arbejder",
    it: "come Lavoro",
    cs: "jako Práce",
    nl: "als Werkend",
    no: "som Arbeider",
    pl: "jako Pracuje",
    sv: "som Arbetar",
    tr: "olarak Çalışıyor",
    uk: "як Працює",
    ro: "ca Lucrând",
    bg: "като Работи",
    be: "як Працуе",
    fi: "kuten Työskentelee",
    pt: "como Trabalhando",
    hr: "kao Rad",
    sl: "kot Delo",
    el: "ως Εργασία",
    hu: "mint Munka",
    sk: "ako Práca",
    ga: "mar Obair",
    ja: "として働いている",
    "zh-CN": "作为工作",
    "zh-TW": "作為工作",
    ko: "작동 중",
    ar: "كعمل",
    ms: "sebagai Bekerja",
    th: "เป็นการทำงาน",
    vi: "như Làm việc",
    tl: "bilang Nagtatrabaho",
    id: "sebagai Bekerja",
    ur: "کام کر رہا ہے",
    fa: "به عنوان کار می کند",
    my: "အလုပ်လုပ်နေသည်",
  },
  asNotWorking: {
    en: "as Not Working",
    es: "como No Funciona",
    fr: "comme Ne fonctionne pas",
    de: "als Nicht funktioniert",
    ru: "как Не работает",
    da: "som Ikke fungerer",
    it: "come Non funziona",
    cs: "jako Nepracuje",
    nl: "als Niet werkend",
    no: "som Ikke fungerer",
    pl: "jako Nie działa",
    sv: "som Inte fungerar",
    tr: "olarak Çalışmıyor",
    uk: "як Не працює",
    ro: "ca Nu funcționează",
    bg: "като Не работи",
    be: "як Не працуе",
    fi: "kuten Ei toimi",
    pt: "como Não Funciona",
    hr: "kao Ne radi",
    sl: "kot Ne deluje",
    el: "ως Δεν λειτουργεί",
    hu: "mint Nem működik",
    sk: "ako Nepracuje",
    ga: "mar Níl ag obair",
    ja: "として機能していません",
    "zh-CN": "作为不工作",
    "zh-TW": "作為不工作",
    ko: "작동하지 않음",
    ar: "كعدم العمل",
    ms: "sebagai Tidak Berfungsi",
    th: "เป็นไม่ทำงาน",
    vi: "như Không hoạt động",
    tl: "bilang Hindi Gumagana",
    id: "sebagai Tidak Bekerja",
    ur: "کام نہیں کر رہا",
    fa: "به عنوان کار نمی کند",
    my: "အလုပ်မလုပ်နေသည်",
  },

  //-------------------- sub homepage -------------------//
  FeaturedStores: {
    en: "Featured Stores",
    es: "Tiendas destacadas",
    fr: "Magasins en vedette",
    de: "Vorgestellte Geschäfte",
    ru: "Избранные магазины",
    da: "Udvalgte butikker",
    it: "Negozi in primo piano",
    cs: "Doporučené obchody",
    nl: "Aanbevolen winkels",
    no: "Utvalgte butikker",
    pl: "Polecane sklepy",
    sv: "Utvalda butiker",
    tr: "Öne Çıkan Mağazalar",
    uk: "Рекомендовані магазини",
    ro: "Magazine recomandate",
    bg: "Препоръчани магазини",
    be: "Рэкамендаваныя магазіны",
    fi: "Suositellut kaupat",
    pt: "Lojas em destaque",
    hr: "Istaknute trgovine",
    sl: "Priporočene trgovine",
    el: "Προτεινόμενα καταστήματα",
    hu: "Kiemelt üzletek",
    sk: "Odporúčané obchody",
    ga: "Siopaí Moltar",
    ja: "注目の店舗",
    "zh-CN": "推荐商店",
    "zh-TW": "推薦商店",
    ko: "주목할 가게",
    ar: "المتاجر المميزة",
    ms: "Kedai Pilihan",
    th: "ร้านค้าแนะนำ",
    vi: "Cửa Hàng Nổi Bật",
    tl: "Mga Tindahan sa Spotlight",
    id: "Toko Unggulan",
    ur: "منتخب اسٹورز",
    fa: "فروشگاه های ویژه",
    my: "အသေးစိတ်ဆိုက်များ",
  },
  TrendingCouponOffers: {
    en: "Trending Coupons & Offers",
    es: "Cupones y ofertas de tendencia",
    fr: "Coupons et offres tendance",
    de: "Trendige Gutscheine und Angebote",
    ru: "Популярные купоны и предложения",
    da: "Trendende kuponer og tilbud",
    it: "Coupon e offerte di tendenza",
    cs: "Trendující kupóny a nabídky",
    nl: "Trending coupons en aanbiedingen",
    no: "Trendende kuponger og tilbud",
    pl: "Trendujące kupony i oferty",
    sv: "Trendande kuponger och erbjudanden",
    tr: "Trend Kuponlar ve Teklifler",
    uk: "Популярні купони та пропозиції",
    ro: "Cupoane și oferte populare",
    bg: "Тенденции купони и оферти",
    be: "Папулярныя купоны і прапановы",
    fi: "Trendaavat kuponit ja tarjoukset",
    pt: "Cupons e ofertas em destaque",
    hr: "Trendi kuponi i ponude",
    sl: "Trendi kuponi in ponudbe",
    el: "Δημοφιλείς κουπόνια και προσφορές",
    hu: "Divatos kuponok és ajánlatok",
    sk: "Trendujúce kupóny a ponuky",
    ga: "Cupóin agus tairiscintí faiseanta",
    ja: "トレンドのクーポンとオファー",
    "zh-CN": "热门优惠券和优惠",
    "zh-TW": "熱門優惠券和優惠",
    ko: "인기있는 쿠폰 및 제안",
    ar: "قسائم وعروض رائجة",
    ms: "Kupon dan Tawaran Trending",
    th: "คูปองและข้อเสนอยอดนิยม",
    vi: "Mã giảm giá và Ưu đãi đang thịnh hành",
    tl: "Mga Coupon at Alo na Trending",
    id: "Kupon dan Penawaran Trending",
    ur: "ٹرینڈنگ کوپن اور پیشکشیں",
    fa: "کوپن ها و پیشنهادات محبوب",
    my: "အသေးစိတ်ကုဒ်နှင့်အများဆုံးကြည့်ပါ",
  },
  WeekFeaturedCouponOffers: {
    en: "This Week Featured Coupons & Offers",
    es: "Esta semana cupones y ofertas destacados",
    fr: "Coupons et offres en vedette cette semaine",
    de: "Diese Woche vorgestellte Gutscheine und Angebote",
    ru: "Избранные купоны и предложения на этой неделе",
    da: "Denne uges fremhævede kuponer og tilbud",
    it: "Coupon e offerte in primo piano di questa settimana",
    cs: " Tento týden doporučené kupóny a nabídky",
    nl: "Deze week aanbevolen coupons en aanbiedingen",
    no: "Utvalgte kuponger og tilbud denne uken",
    pl: "Polecane kupony i oferty w tym tygodniu",
    sv: "Utvalda kuponger och erbjudanden denna vecka",
    tr: "Bu Hafta Öne Çıkan Kuponlar ve Teklifler",
    uk: "Рекомендовані купони та пропозиції цього тижня",
    ro: "Cupoane și oferte recomandate în această săptămână",
    bg: "Препоръчани купони и оферти за тази седмица",
    be: "Падобныя купоны і прапановы на гэтым тыдні",
    fi: "Suositellut kuponit ja tarjoukset tällä viikolla",
    pt: "Cupons e ofertas em destaque esta semana",
    hr: "Istaknuti kuponi i ponude ovog tjedna",
    sl: "Trendi kuponi in ponudbe",
    el: "Δημοφιλείς κουπόνια και προσφορές αυτή την εβδομάδα",
    hu: "Divatos kuponok és ajánlatok ezen a héten",
    sk: "Trendujúce kupóny a ponuky",
    ga: "Cupóin agus tairiscintí faiseanta",
    ja: "今週の注目クーポンとオファー",
    "zh-CN": "本周热门优惠券和优惠",
    "zh-TW": "本週熱門優惠券和優惠",
    ko: "이번 주 인기있는 쿠폰 및 제안",
    ar: "قسائم وعروض رائجة هذا الأسبوع",
    ms: "Kupon dan Tawaran Trending",
    th: "คูปองและข้อเสนอยอดนิยม",
    vi: "Mã giảm giá và Ưu đãi đang thịnh hành",
    tl: "Mga Coupon at Alo na Trending",
    id: "Kupon dan Penawaran Trending",
    ur: "اس ہفتے کی نمایاں کوپن اور پیشکشیں",
    fa: "کوپن ها و پیشنهادات محبوب این هفته",
    my: "ဤအပတ်စိတ်ကုဒ်နှင့်အများဆုံးကြည့်ပါ",
  },
  BrowseCategories: {
    en: "Browse Categories",
    es: "Explorar categorías",
    fr: "Parcourir les catégories",
    de: "Kategorien durchsuchen",
    ru: "Просмотр категорий",
    da: "Gennemse kategorier",
    it: "Sfoglia le categorie",
    cs: "Procházet kategorie",
    nl: "Bladeren door categorieën",
    no: "Bla gjennom kategorier",
    pl: "Przeglądaj kategorie",
    sv: "Bläddra bland kategorier",
    tr: "Kategorilere Göz At",
    uk: "Огляд категорій",
    ro: "Navigați prin categorii",
    bg: "Преглед на категории",
    be: "Агляд катэгорый",
    fi: "Selaa luokkia",
    pt: "Navegar por categorias",
    hr: "Pregledajte kategorije",
    sl: "Prebrskajte kategorije",
    el: "Περιηγηθείτε στις κατηγορίες",
    hu: "Kategóriák böngészése",
    sk: "Prehliadať kategórie",
    ga: "Brabhsáil na Catagóirí",
    ja: "カテゴリを閲覧",
    "zh-CN": "浏览类别",
    "zh-TW": "瀏覽類別",
    ko: "카테고리 탐색",
    ar: "تصفح الفئات",
    ms: "Layari Kategori",
    th: "เรียกดูหมวดหมู่",
    vi: "Duyệt Danh mục",
    tl: "Mag-browse ng Mga Kategorya",
    id: "Jelajahi Kategori",
    ur: "زمرے دیکھیں",
    fa: "مرور دسته بندی ها",
    my: "ကဏ္ဍများကြည့်ပါ",
  },
  SearchCouponDealStore: {
    en: "Search Coupon, Deal & Store",
    es: "Buscar cupón, oferta y tienda",
    fr: "Rechercher coupon, offre et magasin",
    de: "Suche Coupon, Deal & Store",
    ru: "Поиск купона, сделки и магазина",
    da: "Søg efter kupon, tilbud og butik",
    it: "Cerca coupon, offerte e negozio",
    cs: "Hledat kupón, nabídku a obchod",
    nl: "Zoek coupon, deal en winkel",
    no: "Søk kupong, tilbud og butikk",
    pl: "Szukaj kuponu, oferty i sklepu",
    sv: "Sök kupong, erbjudande och butik",
    tr: "Kupon, Fırsat ve Mağaza Ara",
    uk: "Пошук купона, угоди та магазину",
    ro: "Căutare cupon, ofertă și magazin",
    bg: "Търсене на купон, оферта и магазин",
    be: "Пошук купона, прапановы і магазіну",
    fi: "Etsi kuponki, tarjous ja kauppa",
    pt: "Pesquisar cupom, oferta e loja",
    hr: "Pretraži kupon, ponudu i trgovinu",
    sl: "Iskanje kupona, ponudbe in trgovine",
    el: "Αναζήτηση κουπονιού, προσφοράς και καταστήματος",
    hu: "Keresés kupon, ajánlat és üzlet",
    sk: "Hľadať kupón, ponuku a obchod",
    ga: "Cuardaigh Cupán, Cúlra agus Siopa",
    ja: "クーポン、ディール、ストアを検索",
    "zh-CN": "搜索优惠券，交易和商店",
    "zh-TW": "搜索優惠券，交易和商店",
    ko: "쿠폰, 거래 및 상점 검색",
    ar: "البحث عن قسيمة، صفقة ومتجر",
    ms: "Cari Kupon, Tawaran & Kedai",
    th: "ค้นหาคูปอง, ดีล และร้านค้า",
    vi: "Tìm kiếm Mã giảm giá, Ưu đãi & Cửa hàng",
    tl: "Maghanap ng Kupon, Deal & Tindahan",
    id: "Cari Kupon, Penawaran & Toko",
    ur: "کوپن، ڈیل اور اسٹور تلاش کریں",
    fa: "جستجوی کوپن، معامله و فروشگاه",
    my: "ကုတ်လုပ်၊ အရောင်း၊ ဆိုက် ရှာပါ",
  },
  RecentlyAddedStores: {
    en: "Recently Added Stores",
    es: "Tiendas añadidas recientemente",
    fr: "Magasins récemment ajoutés",
    de: "Kürzlich hinzugefügte Geschäfte",
    ru: "Недавно добавленные магазины",
    da: "Nyligt tilføjede butikker",
    it: "Negozi aggiunti di recente",
    cs: "Nedávno přidané obchody",
    nl: "Recent toegevoegde winkels",
    no: "Nylig lagt til butikker",
    pl: "Ostatnio dodane sklepy",
    sv: "Nyligen tillagda butiker",
    tr: "Yeni Eklenen Mağazalar",
    uk: "Нещодавно додані магазини",
    ro: "Magazine adăugate recent",
    bg: "Скоро добавени магазини",
    be: "Нещодавно дададзеныя магазіны",
    fi: "Äskettäin lisätyt kaupat",
    pt: "Lojas recentemente adicionadas",
    hr: "Nedavno dodane trgovine",
    sl: "Nedavno dodane trgovine",
    el: "Πρόσφατα προστεθέντα καταστήματα",
    hu: "Nemrég hozzáadott üzletek",
    sk: "Nedávno pridané obchody",
    ga: "Siopaí a chuir le déanaí",
    ja: "最近追加された店舗",
    "zh-CN": "最近添加的商店",
    "zh-TW": "最近添加的商店",
    ko: "최근 추가된 상점",
    ar: "المتاجر المضافة حديثًا",
    ms: "Kedai yang Baru Ditambah",
    th: "ร้านค้าที่เพิ่มเร็ว",
    vi: "Cửa Hàng Vừa Thêm",
    tl: "Mga Kamakailang Idinagdag na Tindahan",
    id: "Toko yang Baru Ditambahkan",
    ur: "حال ہی مزید اضافہ ہونے والے اسٹورز",
    fa: "فروشگاه های اخیرا اضافه شده",
    my: "မြောက်ရေးသောဆိုက်များ",
  },

  //-------------------- Months -------------------//
  January: {
    en: "January",
    es: "Enero",
    fr: "Janvier",
    de: "Januar",
    ru: "Январь",
    da: "Januar",
    it: "Gennaio",
    cs: "Leden",
    nl: "Januari",
    no: "Januar",
    pl: "Styczeń",
    sv: "Januari",
    tr: "Ocak",
    uk: "Січень",
    ro: "Ianuarie",
    bg: "Януари",
    be: "Студзень",
    fi: "Tammikuu",
    pt: "Janeiro",
    hr: "Siječanj",
    sl: "Januar",
    el: "Ιανουάριος",
    hu: "Január",
    sk: "Január",
    ga: "Eanáir",
    ja: "1月",
    "zh-CN": "一月",
    "zh-TW": "一月",
    ko: "1월",
    ar: "يناير",
    ms: "Januari",
    th: "มกราคม",
    vi: "Tháng Một",
    tl: "Enero",
    id: "Januari",
    ur: "جنوری",
    fa: "ژانویه",
    my: "ဇန်နဝါရီ",
  },
  February: {
    en: "February",
    es: "Febrero",
    fr: "Février",
    de: "Februar",
    ru: "Февраль",
    da: "Februar",
    it: "Febbraio",
    cs: "Únor",
    nl: "Februari",
    no: "Februar",
    pl: "Luty",
    sv: "Februari",
    tr: "Şubat",
    uk: "Лютий",
    ro: "Februarie",
    bg: "Февруари",
    be: "Люты",
    fi: "Helmikuu",
    pt: "Fevereiro",
    hr: "Veljača",
    sl: "Februar",
    el: "Φεβρουάριος",
    hu: "Február",
    sk: "Február",
    ga: "Feabhra",
    ja: "2月",
    "zh-CN": "二月",
    "zh-TW": "二月",
    ko: "2월",
    ar: "فبراير",
    ms: "Februari",
    th: "กุมภาพันธ์",
    vi: "Tháng Hai",
    tl: "Pebrero",
    id: "Februari",
    ur: "فروری",
    fa: "فوریه",
    my: "ဖေဖော်",
  },
  March: {
    en: "March",
    es: "Marzo",
    fr: "Mars",
    de: "März",
    ru: "Март",
    da: "Marts",
    it: "Marzo",
    cs: "Březen",
    nl: "Maart",
    no: "Mars",
    pl: "Marzec",
    sv: "Mars",
    tr: "Mart",
    uk: "Березень",
    ro: "Martie",
    bg: "Март",
    be: "Сакавік",
    fi: "Maaliskuu",
    pt: "Março",
    hr: "Ožujak",
    sl: "Marec",
    el: "Μάρτιος",
    hu: "Március",
    sk: "Marec",
    ga: "Márta",
    ja: "3月",
    "zh-CN": "三月",
    "zh-TW": "三月",
    ko: "3월",
    ar: "مارس",
    ms: "Mac",
    th: "มีนาคม",
    vi: "Tháng Ba",
    tl: "Marso",
    id: "Maret",
    ur: "مارچ",
    fa: "مارس",
    my: "မတ်",
  },
  April: {
    en: "April",
    es: "Abril",
    fr: "Avril",
    de: "April",
    ru: "Апрель",
    da: "April",
    it: "Aprile",
    cs: "Duben",
    nl: "April",
    no: "April",
    pl: "Kwiecień",
    sv: "April",
    tr: "Nisan",
    uk: "Квітень",
    ro: "Aprilie",
    bg: "Април",
    be: "Красавік",
    fi: "Huhtikuu",
    pt: "Abril",
    hr: "Travanj",
    sl: "April",
    el: "Απρίλιος",
    hu: "Április",
    sk: "Apríl",
    ga: "Aibreán",
    ja: "4月",
    "zh-CN": "四月",
    "zh-TW": "四月",
    ko: "4월",
    ar: "أبريل",
    ms: "April",
    th: "เมษายน",
    vi: "Tháng Tư",
    tl: "Abril",
    id: "April",
    ur: "اپریل",
    fa: "آوریل",
    my: "ဧပြီ",
  },
  May: {
    en: "May",
    es: "Mayo",
    fr: "Mai",
    de: "Mai",
    ru: "Май",
    da: "Maj",
    it: "Maggio",
    cs: "Květen",
    nl: "Mei",
    no: "Mai",
    pl: "Maj",
    sv: "Maj",
    tr: "Mayıs",
    uk: "Травень",
    ro: "Mai",
    bg: "Май",
    be: "Май",
    fi: "Toukokuu",
    pt: "Maio",
    hr: "Svibanj",
    sl: "Maj",
    el: "Μάιος",
    hu: "Május",
    sk: "Máj",
    ga: "Bealtaine",
    ja: "5月",
    "zh-CN": "五月",
    "zh-TW": "五月",
    ko: "5월",
    ar: "مايو",
    ms: "Mei",
    th: "พฤษภาคม",
    vi: "Tháng Năm",
    tl: "Mayo",
    id: "Mei",
    ur: "مئی",
    fa: "مه",
    my: "မေ",
  },
  June: {
    en: "June",
    es: "Junio",
    fr: "Juin",
    de: "Juni",
    ru: "Июнь",
    da: "Juni",
    it: "Giugno",
    cs: "Červen",
    nl: "Juni",
    no: "Juni",
    pl: "Czerwiec",
    sv: "Juni",
    tr: "Haziran",
    uk: "Червень",
    ro: "Iunie",
    bg: "Юни",
    be: "Чэрвень",
    fi: "Kesäkuu",
    pt: "Junho",
    hr: "Lipanj",
    sl: "Junij",
    el: "Ιούνιος",
    hu: "Június",
    sk: "Jún",
    ga: "Meitheamh",
    ja: "6月",
    "zh-CN": "六月",
    "zh-TW": "六月",
    ko: "6월",
    ar: "يونيو",
    ms: "Jun",
    th: "มิถุนายน",
    vi: "Tháng Sáu",
    tl: "Hunyo",
    id: "Juni",
    ur: "جون",
    fa: "ژوئن",
    my: "ဇွန်",
  },
  July: {
    en: "July",
    es: "Julio",
    fr: "Juillet",
    de: "Juli",
    ru: "Июль",
    da: "Juli",
    it: "Luglio",
    cs: "Červenec",
    nl: "Juli",
    no: "Juli",
    pl: "Lipiec",
    sv: "Juli",
    tr: "Temmuz",
    uk: "Липень",
    ro: "Iulie",
    bg: "Юли",
    be: "Ліпень",
    fi: "Heinäkuu",
    pt: "Julho",
    hr: "Srpanj",
    sl: "Julij",
    el: "Ιούλιος",
    hu: "Július",
    sk: "Júl",
    ga: "Iúil",
    ja: "7月",
    "zh-CN": "七月",
    "zh-TW": "七月",
    ko: "7월",
    ar: "يوليو",
    ms: "Julai",
    th: "กรกฎาคม",
    vi: "Tháng Bảy",
    tl: "Hulyo",
    id: "Juli",
    ur: "جولائی",
    fa: "جولای",
    my: "ဇူလိုင်",
  },
  August: {
    en: "August",
    es: "Agosto",
    fr: "Août",
    de: "August",
    ru: "Август",
    da: "August",
    it: "Agosto",
    cs: "Srpen",
    nl: "Augustus",
    no: "August",
    pl: "Sierpień",
    sv: "Augusti",
    tr: "Ağustos",
    uk: "Серпень",
    ro: "August",
    bg: "Август",
    be: "Жнівень",
    fi: "Elokuu",
    pt: "Agosto",
    hr: "Kolovoz",
    sl: "Avgust",
    el: "Αύγουστος",
    hu: "Augusztus",
    sk: "August",
    ga: "Lúnasa",
    ja: "8月",
    "zh-CN": "八月",
    "zh-TW": "八月",
    ko: "8월",
    ar: "أغسطس",
    ms: "Ogos",
    th: "สิงหาคม",
    vi: "Tháng Tám",
    tl: "Agosto",
    id: "Agustus",
    ur: "اگست",
    fa: "اوت",
    my: "ဩဂုတ်",
  },
  September: {
    en: "September",
    es: "Septiembre",
    fr: "Septembre",
    de: "September",
    ru: "Сентябрь",
    da: "September",
    it: "Settembre",
    cs: "Září",
    nl: "September",
    no: "September",
    pl: "Wrzesień",
    sv: "September",
    tr: "Eylül",
    uk: "Вересень",
    ro: "Septembrie",
    bg: "Септември",
    be: "Верасень",
    fi: "Syyskuu",
    pt: "Setembro",
    hr: "Rujan",
    sl: "September",
    el: "Σεπτέμβριος",
    hu: "Szeptember",
    sk: "September",
    ga: "Meán Fómhair",
    ja: "9月",
    "zh-CN": "九月",
    "zh-TW": "九月",
    ko: "9월",
    ar: "سبتمبر",
    ms: "September",
    th: "กันยายน",
    vi: "Tháng Chín",
    tl: "Setyembre",
    id: "September",
    ur: "ستمبر",
    fa: "سپتامبر",
    my: "စက်တင်ဘာ",
  },
  October: {
    en: "October",
    es: "Octubre",
    fr: "Octobre",
    de: "Oktober",
    ru: "Октябрь",
    da: "Oktober",
    it: "Ottobre",
    cs: "Říjen",
    nl: "Oktober",
    no: "Oktober",
    pl: "Październik",
    sv: "Oktober",
    tr: "Ekim",
    uk: "Жовтень",
    ro: "Octombrie",
    bg: "Октомври",
    be: "Кастрычнік",
    fi: "Lokakuu",
    pt: "Outubro",
    hr: "Listopad",
    sl: "Oktober",
    el: "Οκτώβριος",
    hu: "Október",
    sk: "Október",
    ga: "Deireadh Fómhair",
    ja: "10月",
    "zh-CN": "十月",
    "zh-TW": "十月",
    ko: "10월",
    ar: "أكتوبر",
    ms: "Oktober",
    th: "ตุลาคม",
    vi: "Tháng Mười",
    tl: "Oktubre",
    id: "Oktober",
    ur: "اکتوبر",
    fa: "اکتبر",
    my: "အောက်တိုဘာ",
  },
  November: {
    en: "November",
    es: "Noviembre",
    fr: "Novembre",
    de: "November",
    ru: "Ноябрь",
    da: "November",
    it: "Novembre",
    cs: "Listopad",
    nl: "November",
    no: "November",
    pl: "Listopad",
    sv: "November",
    tr: "Kasım",
    uk: "Листопад",
    ro: "Noiembrie",
    bg: "Ноември",
    be: "Лістапад",
    fi: "Marraskuu",
    pt: "Novembro",
    hr: "Studeni",
    sl: "November",
    el: "Νοέμβριος",
    hu: "November",
    sk: "November",
    ga: "Samhain",
    ja: "11月",
    "zh-CN": "十一月",
    "zh-TW": "十一月",
    ko: "11월",
    ar: "نوفمبر",
    ms: "November",
    th: "พฤศจิกายน",
    vi: "Tháng Mười Một",
    tl: "Nobyembre",
    id: "November",
    ur: "نومبر",
    fa: "نوامبر",
    my: "နိုဝင်ဘာ",
  },
  December: {
    en: "December",
    es: "Diciembre",
    fr: "Décembre",
    de: "Dezember",
    ru: "Декабрь",
    da: "December",
    it: "Dicembre",
    cs: "Prosinec",
    nl: "December",
    no: "Desember",
    pl: "Grudzień",
    sv: "December",
    tr: "Aralık",
    uk: "Грудень",
    ro: "Decembrie",
    bg: "Декември",
    be: "Снежань",
    fi: "Joulukuu",
    pt: "Dezembro",
    hr: "Prosinac",
    sl: "December",
    el: "Δεκέμβριος",
    hu: "December",
    sk: "December",
    ga: "Nollaig",
    ja: "12月",
    "zh-CN": "十二月",
    "zh-TW": "十二月",
    ko: "12월",
    ar: "ديسمبر",
    ms: "Disember",
    th: "ธันวาคม",
    vi: "Tháng Mười Hai",
    tl: "Disyembre",
    id: "Desember",
    ur: "دسمبر",
    fa: "دسامبر",
    my: "ဒီဇင်ဘာ",
  },
  Jan: {
    en: "Jan",
    es: "Ene",
    fr: "Janv",
    de: "Jan",
    ru: "Янв",
    da: "Jan",
    it: "Gen",
    cs: "Led",
    nl: "Jan",
    no: "Jan",
    pl: "Sty",
    sv: "Jan",
    tr: "Oca",
    uk: "Січ",
    ro: "Ian",
    bg: "Яну",
    be: "Сту",
    fi: "Tam",
    pt: "Jan",
    hr: "Sij",
    sl: "Jan",
    el: "Ιαν",
    hu: "Jan",
    sk: "Jan",
    ga: "Ean",
    ja: "1月",
    "zh-CN": "一月",
    "zh-TW": "一月",
    ko: "1월",
    ar: "يناير",
    ms: "Jan",
    th: "ม.ค.",
    vi: "Thg 1",
    tl: "Ene",
    id: "Jan",
    ur: "جن",
    fa: "ژانویه",
    my: "ဇန်",
  },
  Feb: {
    en: "Feb",
    es: "Feb",
    fr: "Fév",
    de: "Feb",
    ru: "Фев",
    da: "Feb",
    it: "Feb",
    cs: "Úno",
    nl: "Feb",
    no: "Feb",
    pl: "Lut",
    sv: "Feb",
    tr: "Şub",
    uk: "Лют",
    ro: "Feb",
    bg: "Фев",
    be: "Лют",
    fi: "Hel",
    pt: "Fev",
    hr: "Vel",
    sl: "Feb",
    el: "Φεβ",
    hu: "Feb",
    sk: "Feb",
    ga: "Fea",
    ja: "2月",
    "zh-CN": "二月",
    "zh-TW": "二月",
    ko: "2월",
    ar: "فبراير",
    ms: "Peb",
    th: "ก.พ.",
    vi: "Thg 2",
    tl: "Peb",
    id: "Feb",
    ur: "فر",
    fa: "فوریه",
    my: "ဖေ",
  },
  Mar: {
    en: "Mar",
    es: "Mar",
    fr: "Mar",
    de: "Mär",
    ru: "Мар",
    da: "Mar",
    it: "Mar",
    cs: "Bře",
    nl: "Mrt",
    no: "Mar",
    pl: "Mar",
    sv: "Mar",
    tr: "Mar",
    uk: "Бер",
    ro: "Mar",
    bg: "Мар",
    be: "Сак",
    fi: "Maa",
    pt: "Mar",
    hr: "Ožu",
    sl: "Mar",
    el: "Μάρ",
    hu: "Már",
    sk: "Mar",
    ga: "Már",
    ja: "3月",
    "zh-CN": "三月",
    "zh-TW": "三月",
    ko: "3월",
    ar: "مارس",
    ms: "Mar",
    th: "มี.ค.",
    vi: "Thg 3",
    tl: "Mar",
    id: "Mar",
    ur: "مار",
    fa: "مارس",
    my: "မတ်",
  },
  Apr: {
    en: "Apr",
    es: "Abr",
    fr: "Avr",
    de: "Apr",
    ru: "Апр",
    da: "Apr",
    it: "Apr",
    cs: "Dub",
    nl: "Apr",
    no: "Apr",
    pl: "Kwi",
    sv: "Apr",
    tr: "Nis",
    uk: "Кві",
    ro: "Apr",
    bg: "Апр",
    be: "Кра",
    fi: "Huh",
    pt: "Abr",
    hr: "Tra",
    sl: "Apr",
    el: "Απρ",
    hu: "Ápr",
    sk: "Apr",
    ga: "Aib",
    ja: "4月",
    "zh-CN": "四月",
    "zh-TW": "四月",
    ko: "4월",
    ar: "أبريل",
    ms: "Abr",
    th: "เม.ย.",
    vi: "Thg 4",
    tl: "Abr",
    id: "Apr",
    ur: "اپریل",
    fa: "آوریل",
    my: "ဧပြ",
  },
  Jun: {
    en: "Jun",
    es: "Jun",
    fr: "Juin",
    de: "Jun",
    ru: "Июн",
    da: "Jun",
    it: "Giu",
    cs: "Čer",
    nl: "Jun",
    no: "Jun",
    pl: "Cze",
    sv: "Jun",
    tr: "Haz",
    uk: "Чер",
    ro: "Iun",
    bg: "Юни",
    be: "Чэр",
    fi: "Kes",
    pt: "Jun",
    hr: "Lip",
    sl: "Jun",
    el: "Ιού",
    hu: "Jún",
    sk: "Jún",
    ga: "Mei",
    ja: "6月",
    "zh-CN": "六月",
    "zh-TW": "六月",
    ko: "6월",
    ar: "يونيو",
    ms: "Jun",
    th: "มิ.ย.",
    vi: "Thg 6",
    tl: "Hun",
    id: "Jun",
    ur: "جون",
    fa: "ژوئن",
    my: "ဇွန်",
  },
  Jul: {
    en: "Jul",
    es: "Jul",
    fr: "Juil",
    de: "Jul",
    ru: "Июл",
    da: "Jul",
    it: "Lug",
    cs: "Čvc",
    nl: "Jul",
    no: "Jul",
    pl: "Lip",
    sv: "Jul",
    tr: "Tem",
    uk: "Лип",
    ro: "Iul",
    bg: "Юли",
    be: "Ліп",
    fi: "Hei",
    pt: "Jul",
    hr: "Srp",
    sl: "Jul",
    el: "Ιού",
    hu: "Júl",
    sk: "Júl",
    ga: "Iúi",
    ja: "7月",
    "zh-CN": "七月",
    "zh-TW": "七月",
    ko: "7월",
    ar: "يوليو",
    ms: "Jul",
    th: "ก.ค.",
    vi: "Thg 7",
    tl: "Hul",
    id: "Jul",
    ur: "جول",
    fa: "جولای",
    my: "ဇူလိုင်",
  },
  Aug: {
    en: "Aug",
    es: "Ago",
    fr: "Aoû",
    de: "Aug",
    ru: "Авг",
    da: "Aug",
    it: "Ago",
    cs: "Srp",
    nl: "Aug",
    no: "Aug",
    pl: "Sie",
    sv: "Aug",
    tr: "Ağu",
    uk: "Сер",
    ro: "Aug",
    bg: "Авг",
    be: "Жні",
    fi: "Elo",
    pt: "Ago",
    hr: "Kol",
    sl: "Avg",
    el: "Αύγ",
    hu: "Aug",
    sk: "Aug",
    ga: "Lún",
    ja: "8月",
    "zh-CN": "八月",
    "zh-TW": "八月",
    ko: "8월",
    ar: "أغسطس",
    ms: "Ogo",
    th: "ส.ค.",
    vi: "Thg 8",
    tl: "Ago",
    id: "Agu",
    ur: "اگس",
    fa: "اوت",
    my: "ဩဂုတ်",
  },
  Sep: {
    en: "Sep",
    es: "Sep",
    fr: "Sep",
    de: "Sep",
    ru: "Сен",
    da: "Sep",
    it: "Set",
    cs: "Zář",
    nl: "Sep",
    no: "Sep",
    pl: "Wrz",
    sv: "Sep",
    tr: "Eyl",
    uk: "Вер",
    ro: "Sep",
    bg: "Сеп",
    be: "Вер",
    fi: "Syys",
    pt: "Set",
    hr: "Ruj",
    sl: "Sep",
    el: "Σεπ",
    hu: "Sze",
    sk: "Sep",
    ga: "Meá",
    ja: "9月",
    "zh-CN": "九月",
    "zh-TW": "九月",
    ko: "9월",
    ar: "سبتمبر",
    ms: "Sep",
    th: "ก.ย.",
    vi: "Thg 9",
    tl: "Set",
    id: "Sep",
    ur: "ست",
    fa: "سپتامبر",
    my: "စက်",
  },
  Oct: {
    en: "Oct",
    es: "Oct",
    fr: "Oct",
    de: "Okt",
    ru: "Окт",
    da: "Okt",
    it: "Ott",
    cs: "Říj",
    nl: "Okt",
    no: "Okt",
    pl: "Paź",
    sv: "Okt",
    tr: "Eki",
    uk: "Жов",
    ro: "Oct",
    bg: "Окт",
    be: "Кас",
    fi: "Lok",
    pt: "Out",
    hr: "Lis",
    sl: "Okt",
    el: "Οκτ",
    hu: "Okt",
    sk: "Okt",
    ga: "Dei",
    ja: "10月",
    "zh-CN": "十月",
    "zh-TW": "十月",
    ko: "10월",
    ar: "أكتوبر",
    ms: "Okt",
    th: "ต.ค.",
    vi: "Thg 10",
    tl: "Okt",
    id: "Okt",
    ur: "اکت",
    fa: "اکتبر",
    my: "အောက်",
  },
  Nov: {
    en: "Nov",
    es: "Nov",
    fr: "Nov",
    de: "Nov",
    ru: "Ноя",
    da: "Nov",
    it: "Nov",
    cs: "Lis",
    nl: "Nov",
    no: "Nov",
    pl: "Lis",
    sv: "Nov",
    tr: "Kas",
    uk: "Лис",
    ro: "Nov",
    bg: "Ное",
    be: "Ліс",
    fi: "Sam",
    pt: "Nov",
    hr: "Sam",
    sl: "Nov",
    el: "Νοέ",
    hu: "Nov",
    sk: "Nov",
    ga: "Sam",
    ja: "11月",
    "zh-CN": "十一月",
    "zh-TW": "十一月",
    ko: "11월",
    ar: "نوفمبر",
    ms: "Nov",
    th: "พ.ย.",
    vi: "Thg 11",
    tl: "Nob",
    id: "Nov",
    ur: "نوم",
    fa: "نوامبر",
    my: "နို",
  },
  Dec: {
    en: "Dec",
    es: "Dic",
    fr: "Déc",
    de: "Dez",
    ru: "Дек",
    da: "Dec",
    it: "Dic",
    cs: "Pro",
    nl: "Dec",
    no: "Des",
    pl: "Gru",
    sv: "Dec",
    tr: "Ara",
    uk: "Гру",
    ro: "Dec",
    bg: "Дек",
    be: "Сне",
    fi: "Jou",
    pt: "Dez",
    hr: "Pro",
    sl: "Dec",
    el: "Δεκ",
    hu: "Dec",
    sk: "Dec",
    ga: "Nol",
    ja: "12月",
    "zh-CN": "十二月",
    "zh-TW": "十二月",
    ko: "12월",
    ar: "ديسمبر",
    ms: "Dis",
    th: "ธ.ค.",
    vi: "Thg 12",
    tl: "Dis",
    id: "Des",
    ur: "دس",
    fa: "دسامبر",
    my: "ဒီ",
  },
};
