export const words = {
  //-------------------- params -------------------//
  All: {
    en: "All",
    ru: "Все",
    ar: "الكل",
    pt: "Todos",
    ja: "すべて",
  },
  Coupon: {
    en: "Coupon",
    ru: "Купон",
    ar: "كوبون",
    pt: "Cupom",
    ja: "クーポン",
  },
  Coupons: {
    en: "Coupons",
    ru: "Купоны",
    ar: "كوبونات",
    pt: "Cupons",
    ja: "クーポン",
  },
  CouponCode: {
    en: "Coupon Code",
    ru: "Промокод",
    ar: "كود القسيمة",
    pt: "Código do cupom",
    ja: "クーポンコード",
  },
  Deal: {
    en: "Deal",
    ru: "Сделка",
    ar: "صفقة",
    pt: "Acordo",
    ja: "ディール",
  },
  Deals: {
    en: "Deals",
    ru: "Сделки",
    ar: "صفقات",
    pt: "Ofertas",
    ja: "お得",
  },

  //-------------------- navbar -------------------//

  Home: {
    en: "Home",
    ru: "Главная",
    ar: "الصفحة الرئيسية",
    pt: "Casa",
    ja: "ホーム",
  },
  Stores: {
    en: "Stores",
    ru: "Магазины",
    ar: "المتاجر",
    pt: "Lojas",
    ja: "店舗",
  },
  TopBrands: {
    en: "Top Brands",
    ru: "Топ бренды",
    ar: "أفضل العلامات التجارية",
    pt: "Principais marcas",
    ja: "トップブランド",
  },
  TopOffers: {
    en: "Top Offers",
    ru: "Топ предложения",
    ar: "أفضل العروض",
    pt: "Principais ofertas",
    ja: "トップオファー",
  },

  Categories: {
    en: "Categories",
    ru: "Категории",
    ar: "الفئات",
    pt: "Categorias",
    ja: "カテゴリー",
  },
  Tags: {
    en: "Tags",
    ru: "Теги",
    ar: "العلامات",
    pt: "Tags",
    ja: "タグ",
  },

  Search: {
    en: "Search",
    ru: "Поиск",
    ar: "بحث",
    pt: "Procurar",
    ja: "サーチ",
  },

  AddDeal: {
    en: "Add Deal",
    ru: "Добавить сделку",
    ar: "أضف صفقة",
    pt: "Adicionar acordo",
    ja: "ディールを追加",
  },

  //-------------------- footer -------------------//

  HaveANiceDay: {
    en: "Have a nice day!",
    ru: "Хорошего дня!",
    ar: "أتمنى لك يوما سعيدا!",
    pt: "Tenha um bom dia!",
    ja: "良い一日を！",
  },
  GlobalNetwork: {
    en: "Global Network",
    ru: "Глобальная сеть",
    ar: "الشبكة العالمية",
    pt: "Rede global",
    ja: "グローバルネットワーク",
  },

  ImportantLinks: {
    en: "Important Links",
    ru: "Важные ссылки",
    ar: "روابط مهمة",
    pt: "Links importantes",
    ja: "重要なリンク",
  },

  AboutUs: {
    en: "About Us",
    ru: "О нас",
    ar: "معلومات عنا",
    pt: "Sobre nós",
    ja: "私たちについて",
  },
  ContactUs: {
    en: "Contact Us",
    ru: "Связаться с нами",
    ar: "اتصل بنا",
    pt: "Contate-Nos",
    ja: "お問い合わせ",
  },
  PrivacyPolicy: {
    en: "Privacy Policy",
    ru: "Политика конфиденциальности",
    ar: "سياسة الخصوصية",
    pt: "Política de Privacidade",
    ja: "プライバシーポリシー",
  },
  TermsAndConditions: {
    en: "Terms and Conditions",
    ru: "Условия и положения",
    ar: "البنود و الشروط",
    pt: "Termos e Condições",
    ja: "利用規約",
  },
  Disclaimer: {
    en: "Disclaimer",
    ru: "Отказ от ответственности",
    ar: "إخلاء المسؤولية",
    pt: "Aviso Legal",
    ja: "免責事項",
  },
  AllStores: {
    en: "All Stores",
    ru: "Все магазины",
    ar: "جميع المتاجر",
    pt: "Todas as lojas",
    ja: "すべての店舗",
  },
  TopStores: {
    en: "Top Stores",
    ru: "Топ магазины",
    ar: "أفضل المتاجر",
    pt: "Lojas principais",
    ja: "トップストア",
  },
  BestOffers: {
    en: "Best Offers",
    ru: "Лучшие предложения",
    ar: "أفضل العروض",
    pt: "Melhores ofertas",
    ja: "ベストオファー",
  },
  SubmitACoupon: {
    en: "Submit a Coupon",
    ru: "Отправить купон",
    ar: "إرسال قسيمة",
    pt: "Enviar um cupom",
    ja: "クーポンを提出する",
  },

  //-------------------- auth -------------------//

  Login: {
    en: "Login",
    ru: "Войти",
    ar: "تسجيل الدخول",
    pt: "Entrar",
    ja: "ログイン",
  },
  or: {
    en: "or",
    ru: "или",
    ar: "أو",
    pt: "ou",
    ja: "または",
  },
  Signup: {
    en: "Signup",
    ru: "Зарегистрироваться",
    ar: "سجل",
    pt: "Inscrever-se",
    ja: "サインアップ",
  },
  Logout: {
    en: "Logout",
    ru: "Выйти",
    ar: "الخروج",
    pt: "Sair",
    ja: "ログアウト",
  },
  //-------------------- storepage -------------------//
  Ratings: {
    en: "Ratings",
    ru: "Рейтинги",
    ar: "تصنيفات",
    pt: "Classificações",
    ja: "評価",
  },
  Content: {
    en: "Content",
    ru: "Содержание",
    ar: "محتوى",
    pt: "Conteúdo",
    ja: "コンテンツ",
  },

  Visit: {
    en: "Visit",
    ru: "Посещение",
    ar: "زيارة",
    pt: "Visita",
    ja: "訪問",
  },
  IsItWorking: {
    en: "Is it working?",
    ru: "Работает ли это?",
    ar: "هل هذا يعمل؟",
    pt: "Está funcionando?",
    ja: "それは機能していますか？",
  },
  Yes: {
    en: "Yes",
    ru: "Да",
    ar: "نعم",
    pt: "Sim",
    ja: "はい",
  },
  No: {
    en: "No",
    ru: "Нет",
    ar: "لا",
    pt: "Não",
    ja: "いいえ",
  },
  AddCoupon: {
    en: "Add Coupon",
    ru: "Добавить купон",
    ar: "أضف كوبون",
    pt: "Adicionar cupom",
    ja: "クーポンを追加",
  },
  TotalOffers: {
    en: "Total Offers",
    ru: "Всего предложений",
    ar: "مجموع العروض",
    pt: "Ofertas totais",
    ja: "合計オファー",
  },
  SitewideOffers: {
    en: "Sitewide Offers",
    ru: "Предложения на всем сайте",
    ar: "عروض على موقع الويب",
    pt: "Ofertas em todo o site",
    ja: "サイト全体のオファー",
  },
  BestDiscount: {
    en: "Best Discount",
    ru: "Лучшая скидка",
    ar: "أفضل خصم",
    pt: "Melhor desconto",
    ja: "最高の割引",
  },
  ViewAllStores: {
    en: "View All Stores",
    ru: "Просмотреть все магазины",
    ar: "عرض جميع المتاجر",
    pt: "Ver todas as lojas",
    ja: "すべての店舗を表示",
  },
  ViewMore: {
    en: "View More",
    ru: "Посмотреть больше",
    ar: "عرض المزيد",
    pt: "Ver mais",
    ja: "もっと見る",
  },
  PopularStores: {
    en: "Popular Stores",
    ru: "Популярные магазины",
    ar: "المتاجر الشهيرة",
    pt: "Lojas populares",
    ja: "人気の店舗",
  },
  OffersFromSimilarStores: {
    en: "Offers from Similar Stores",
    ru: "Предложения от похожих магазинов",
    ar: "عروض من متاجر مماثلة",
    pt: "Ofertas de lojas semelhantes",
    ja: "類似ストアからのオファー",
  },

  SHOWCODE: {
    en: "SHOW CODE",
    ru: "ПОКАЗАТЬ КОД",
    ar: "عرض الكود",
    pt: "MOSTRAR CÓDIGO",
    ja: "コードを表示",
  },
  VIEWDEAL: {
    en: "VIEW DEAL",
    ru: "ПОСМОТРЕТЬ СДЕЛКУ",
    ar: "عرض الصفقة",
    pt: "VER ACORDO",
    ja: "ディールを見る",
  },
  GoToStore: {
    en: "Go to Store",
    ru: "Перейти в магазин",
    ar: "انتقل إلى المتجر",
    pt: "Ir para a loja",
    ja: "ストアに移動",
  },
  LimitedTime: {
    en: "Limited Time",
    ru: "Ограниченное время",
    ar: "وقت محدود",
    pt: "Tempo limitado",
    ja: "期間限定",
  },
  Step: {
    en: "Step",
    ru: "Шаг",
    ar: "خطوة",
    pt: "Passo",
    ja: "ステップ",
  },
  ApplyCoupon: {
    en: "Apply Coupon",
    ru: "Применить купон",
    ar: "تطبيق القسيمة",
    pt: "Aplicar cupom",
    ja: "クーポンを適用",
  },
  viewsLastWeek: {
    en: "views last week",
    ru: "просмотры на прошлой неделе",
    ar: "الآراء الأسبوع الماضي",
    pt: "visualizações na última semana",
    ja: "先週のビュー",
  },
  ViewOffers: {
    en: "View Offers",
    ru: "Просмотреть предложения",
    ar: "عرض العروض",
    pt: "Ver ofertas",
    ja: "オファーを表示",
  },
  ViewAll: {
    en: "View All",
    ru: "Посмотреть все",
    ar: "عرض الكل",
    pt: "Ver tudo",
    ja: "すべて表示",
  },
  SimilarCoupons: {
    en: "Similar Coupons",
    ru: "Похожие купоны",
    ar: "كوبونات مماثلة",
    pt: "Cupons semelhantes",
    ja: "類似のクーポン",
  },
  SimilarStoresYouMayLike: {
    en: "Similar Stores You May Like",
    ru: "Похожие магазины, которые вам могут понравиться",
    ar: "المتاجر المماثلة التي قد تعجبك",
    pt: "Lojas semelhantes que você pode gostar",
    ja: "気に入るかもしれない似たような店",
  },
  StoreStats: {
    en: "Store Stats",
    ru: "Статистика магазина",
    ar: "إحصائيات المتجر",
    pt: "Estatísticas da loja",
    ja: "店舗統計",
  },
  Verified: {
    en: "Verified",
    ru: "Проверено",
    ar: "تم التحقق",
    pt: "Verificado",
    ja: "確認済み",
  },
  Off: {
    en: "Off",
    ru: "Скидка",
    ar: "إيقاف",
    pt: "Desligado",
    ja: "オフ",
  },
  NoStoresFound: {
    en: "No stores found",
    ru: "Магазины не найдены",
    ar: "لم يتم العثور على المتاجر",
    pt: "Nenhuma loja encontrada",
    ja: "ストアが見つかりません",
  },
  CouponUsageHistory: {
    en: "Coupon Usage History",
    ru: "История использования купона",
    ar: "تاريخ استخدام القسيمة",
    pt: "Histórico de uso do cupom",
    ja: "クーポン使用履歴",
  },
  AShopperMarkedTheOffer: {
    en: "A shopper marked the offer as working",
    ru: "Покупатель отметил предложение как работающее",
    ar: "علام تسوق العرض كعمل",
    pt: "Um comprador marcou a oferta como funcionando",
    ja: "ショッパーはオファーを動作中としてマークしました",
  },
  asWorking: {
    en: "as Working",
    ru: "как Работает",
    ar: "كعمل",
    pt: "como Funcionando",
    ja: "として機能しています",
  },

  asNotWorking: {
    en: "as Not Working",
    ru: "как Не работает",
    ar: "كعمل",
    pt: "como Não Funcionando",
    ja: "として機能していません",
  },

  //-------------------- sub homepage -------------------//
  FeaturedStores: {
    en: "Featured Stores",
    ru: "Избранные магазины",
    ar: "المتاجر المميزة",
    pt: "Lojas em destaque",
    ja: "注目の店舗",
  },
  TrendingCouponOffers: {
    en: "Trending Coupon Offers",
    ru: "Популярные купоны",
    ar: "عروض القسيمة الرائجة",
    pt: "Ofertas de cupons em alta",
    ja: "トレンドのクーポンオファー",
  },
  WeekFeaturedCouponOffers: {
    en: "This Week Featured Coupon Offers",
    ru: "Избранные купоны на этой неделе",
    ar: "عروض القسيمة المميزة هذا الأسبوع",
    pt: "Ofertas de cupons em destaque desta semana",
    ja: "今週の注目のクーポンオファー",
  },
  BrowseTags: {
    en: "Browse Tags",
    ru: "Просмотр тегов",
    ar: "تصفح العلامات",
    pt: "Navegar por tags",
    ja: "タグを参照",
  },
  SearchCouponDealStore: {
    en: "Search for a Coupon, Deal or Store",
    ru: "Поиск купона, сделки или магазина",
    ar: "البحث عن قسيمة أو صفقة أو متجر",
    pt: "Pesquisar um cupom, oferta ou loja",
    ja: "クーポン、ディール、ストアを検索",
  },
  RecentlyAddedStores: {
    en: "Recently Added Stores",
    ru: "Недавно добавленные магазины",
    ar: "المتاجر المضافة حديثًا",
    pt: "Lojas recentemente adicionadas",
    ja: "最近追加されたストア",
  },

  //-------------------- Months -------------------//
  January: {
    en: "January",
    ru: "Январь",
    ar: "يناير",
    pt: "Janeiro",
    ja: "1月",
  },
  February: {
    en: "February",
    ru: "Февраль",
    ar: "فبراير",
    pt: "Fevereiro",
    ja: "2月",
  },
  March: {
    en: "March",
    ru: "Март",
    ar: "مارس",
    pt: "Março",
    ja: "3月",
  },
  April: {
    en: "April",
    ru: "Апрель",
    ar: "أبريل",
    pt: "Abril",
    ja: "4月",
  },
  May: {
    en: "May",
    ru: "Май",
    ar: "مايو",
    pt: "Maio",
    ja: "5月",
  },
  June: {
    en: "June",
    ru: "Июнь",
    ar: "يونيو",
    pt: "Junho",
    ja: "6月",
  },
  July: {
    en: "July",
    ru: "Июль",
    ar: "يوليو",
    pt: "Julho",
    ja: "7月",
  },
  August: {
    en: "August",
    ru: "Август",
    ar: "أغسطس",
    pt: "Agosto",
    ja: "8月",
  },
  September: {
    en: "September",
    ru: "Сентябрь",
    ar: "سبتمبر",
    pt: "Setembro",
    ja: "9月",
  },
  October: {
    en: "October",
    ru: "Октябрь",
    ar: "أكتوبر",
    pt: "Outubro",
    ja: "10月",
  },
  November: {
    en: "November",
    ru: "Ноябрь",
    ar: "نوفمبر",
    pt: "Novembro",
    ja: "11月",
  },
  December: {
    en: "December",
    ru: "Декабрь",
    ar: "ديسمبر",
    pt: "Dezembro",
    ja: "12月",
  },

  //--------------- Short

  Jan: {
    en: "Jan",
    ru: "Янв",
    ar: "يناير",
    pt: "Jan",
    ja: "1月",
  },
  Feb: {
    en: "Feb",
    ru: "Фев",
    ar: "فبراير",
    pt: "Fev",
    ja: "2月",
  },
  Mar: {
    en: "Mar",
    ru: "Мар",
    ar: "مارس",
    pt: "Mar",
    ja: "3月",
  },
  Apr: {
    en: "Apr",
    ru: "Апр",
    ar: "أبريل",
    pt: "Abr",
    ja: "4月",
  },
  Jun: {
    en: "Jun",
    ru: "Июн",
    ar: "يونيو",
    pt: "Jun",
    ja: "6月",
  },
  Jul: {
    en: "Jul",
    ru: "Июл",
    ar: "يوليو",
    pt: "Jul",
    ja: "7月",
  },
  Aug: {
    en: "Aug",
    ru: "Авг",
    ar: "أغسطس",
    pt: "Ago",
    ja: "8月",
  },
  Sep: {
    en: "Sep",
    ru: "Сен",
    ar: "سبتمبر",
    pt: "Set",
    ja: "9月",
  },
  Oct: {
    en: "Oct",
    ru: "Окт",
    ar: "أكتوبر",
    pt: "Out",
    ja: "10月",
  },
  Nov: {
    en: "Nov",
    ru: "Ноя",
    ar: "نوفمبر",
    pt: "Nov",
    ja: "11月",
  },
  Dec: {
    en: "Dec",
    ru: "Дек",
    ar: "ديسمبر",
    pt: "Dez",
    ja: "12月",
  },
};
