import React from "react";
import "@repo/ui/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MainLayout from "@repo/ui/layouts/MainLayout";
// import SessionWrapper from "@repo/ui/lib/SessionWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Docs",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // <SessionWrapper>
    <html lang="en">
      <MainLayout>{children}</MainLayout>
    </html>
    // </SessionWrapper>
  );
}
